class ErrorCode:
    LIVE_HISTORY_NOT_FOUND = "LIVE_HISTORY_NOT_FOUND"
    LIVE_HISTORY_UPDATE_FAILED = "LIVE_HISTORY_UPDATE_FAILED"
    INVALID_DATE_FORMAT = "INVALID_DATE_FORMAT"


class DomainErrorCode:
    LIVE_HISTORY_NOT_FOUND_ERROR = "Live history not found."
    LIVE_HISTORY_UPDATE_ERROR = "Failed to update live history."
    INVALID_DATE_FORMAT_ERROR = "Invalid date format."
