/**
 * Curated emoji set used by the Page48 emoji picker.
 *
 * Kept as local data instead of a picker library so the picker needs no extra
 * dependency and never fetches emoji data from a CDN.
 */

export interface Emoji {
	/** The emoji glyph, e.g. "😀". */
	char: string;
	/** English label, used as the tooltip and the search haystack. */
	label: string;
	/** Extra search terms (e.g. Indonesian equivalents). */
	aliases?: string;
}

export interface EmojiCategory {
	/** Also the i18n key suffix: `page48.emoji.<id>`. */
	id: string;
	/** Glyph shown on the category tab. */
	icon: string;
	emojis: Emoji[];
}

const e = (char: string, label: string, aliases?: string): Emoji =>
	aliases ? { char, label, aliases } : { char, label };

export const EMOJI_CATEGORIES: EmojiCategory[] = [
	{
		id: 'smileys',
		icon: '😀',
		emojis: [
			e('😀', 'grinning face', 'senyum'),
			e('😃', 'grinning face with big eyes', 'senang'),
			e('😄', 'grinning face with smiling eyes'),
			e('😁', 'beaming face'),
			e('😆', 'laughing squinting face', 'tertawa'),
			e('😅', 'grinning face with sweat', 'gugup'),
			e('😂', 'face with tears of joy', 'tertawa ngakak'),
			e('🤣', 'rolling on the floor laughing', 'ngakak'),
			e('🙂', 'slightly smiling face'),
			e('😊', 'smiling face with smiling eyes', 'malu'),
			e('😇', 'smiling face with halo', 'malaikat'),
			e('🙃', 'upside down face'),
			e('😉', 'winking face', 'kedip'),
			e('😌', 'relieved face', 'lega'),
			e('😍', 'smiling face with heart eyes', 'cinta suka'),
			e('🥰', 'smiling face with hearts', 'sayang'),
			e('😘', 'face blowing a kiss', 'cium'),
			e('😋', 'savoring food', 'enak'),
			e('😜', 'winking face with tongue'),
			e('🤪', 'zany face', 'gila'),
			e('🤩', 'star struck', 'kagum'),
			e('🥳', 'partying face', 'pesta'),
			e('😎', 'smiling face with sunglasses', 'keren'),
			e('🤓', 'nerd face', 'kutu buku'),
			e('🧐', 'face with monocle'),
			e('😏', 'smirking face'),
			e('😒', 'unamused face', 'sebal'),
			e('😔', 'pensive face', 'sedih'),
			e('😞', 'disappointed face', 'kecewa'),
			e('😟', 'worried face', 'khawatir'),
			e('😕', 'confused face', 'bingung'),
			e('🥺', 'pleading face', 'memohon'),
			e('😢', 'crying face', 'menangis'),
			e('😭', 'loudly crying face', 'nangis'),
			e('😤', 'face with steam from nose'),
			e('😠', 'angry face', 'marah'),
			e('😡', 'pouting face', 'murka'),
			e('🤬', 'face with symbols on mouth', 'umpatan'),
			e('😳', 'flushed face', 'salah tingkah'),
			e('🥵', 'hot face', 'panas'),
			e('🥶', 'cold face', 'dingin'),
			e('😱', 'face screaming in fear', 'kaget'),
			e('😨', 'fearful face', 'takut'),
			e('🤔', 'thinking face', 'berpikir'),
			e('🤭', 'face with hand over mouth'),
			e('🤫', 'shushing face', 'diam'),
			e('😴', 'sleeping face', 'tidur'),
			e('🤤', 'drooling face', 'ngiler'),
			e('😵', 'dizzy face', 'pusing'),
			e('🤗', 'hugging face', 'peluk'),
			e('😷', 'face with medical mask', 'sakit'),
			e('🤒', 'face with thermometer', 'demam'),
			e('🤕', 'face with head bandage', 'luka'),
			e('🤠', 'cowboy hat face'),
			e('🥴', 'woozy face'),
			e('🤢', 'nauseated face', 'mual'),
			e('🤮', 'face vomiting', 'muntah'),
			e('🤧', 'sneezing face', 'bersin'),
			e('😈', 'smiling face with horns', 'setan'),
			e('👻', 'ghost', 'hantu'),
			e('💀', 'skull', 'tengkorak'),
			e('👽', 'alien'),
			e('🤖', 'robot'),
			e('💩', 'pile of poo', 'tahi')
		]
	},
	{
		id: 'gestures',
		icon: '👋',
		emojis: [
			e('👋', 'waving hand', 'melambai halo'),
			e('🤚', 'raised back of hand'),
			e('🖐️', 'hand with fingers splayed'),
			e('✋', 'raised hand', 'stop'),
			e('🖖', 'vulcan salute'),
			e('👌', 'ok hand'),
			e('🤏', 'pinching hand'),
			e('✌️', 'victory hand', 'damai'),
			e('🤞', 'crossed fingers', 'semoga'),
			e('🤟', 'love you gesture'),
			e('🤘', 'sign of the horns', 'rock'),
			e('🤙', 'call me hand'),
			e('👈', 'backhand index pointing left'),
			e('👉', 'backhand index pointing right'),
			e('👆', 'backhand index pointing up'),
			e('👇', 'backhand index pointing down'),
			e('☝️', 'index pointing up'),
			e('👍', 'thumbs up', 'jempol bagus setuju'),
			e('👎', 'thumbs down', 'jelek'),
			e('✊', 'raised fist'),
			e('👊', 'oncoming fist', 'tonjok'),
			e('👏', 'clapping hands', 'tepuk tangan'),
			e('🙌', 'raising hands', 'hore'),
			e('👐', 'open hands'),
			e('🤲', 'palms up together', 'berdoa'),
			e('🤝', 'handshake', 'jabat tangan'),
			e('🙏', 'folded hands', 'terima kasih doa'),
			e('✍️', 'writing hand', 'menulis'),
			e('💅', 'nail polish', 'kuku'),
			e('🤳', 'selfie'),
			e('💪', 'flexed biceps', 'kuat semangat'),
			e('🦵', 'leg'),
			e('🦶', 'foot'),
			e('👀', 'eyes', 'lihat'),
			e('👅', 'tongue', 'lidah'),
			e('👄', 'mouth', 'mulut'),
			e('🫶', 'heart hands', 'cinta')
		]
	},
	{
		id: 'hearts',
		icon: '❤️',
		emojis: [
			e('❤️', 'red heart', 'cinta hati'),
			e('🧡', 'orange heart'),
			e('💛', 'yellow heart'),
			e('💚', 'green heart'),
			e('💙', 'blue heart'),
			e('💜', 'purple heart'),
			e('🖤', 'black heart'),
			e('🤍', 'white heart'),
			e('🤎', 'brown heart'),
			e('💔', 'broken heart', 'patah hati'),
			e('❣️', 'heart exclamation'),
			e('💕', 'two hearts', 'cinta'),
			e('💞', 'revolving hearts'),
			e('💓', 'beating heart'),
			e('💗', 'growing heart'),
			e('💖', 'sparkling heart'),
			e('💘', 'heart with arrow'),
			e('💝', 'heart with ribbon'),
			e('💟', 'heart decoration'),
			e('💯', 'hundred points', 'seratus mantap'),
			e('🔥', 'fire', 'api keren'),
			e('✨', 'sparkles', 'berkilau'),
			e('💫', 'dizzy'),
			e('⭐', 'star', 'bintang'),
			e('🌟', 'glowing star'),
			e('💥', 'collision', 'boom'),
			e('🎉', 'party popper', 'selamat'),
			e('🎊', 'confetti ball'),
			e('🎈', 'balloon', 'balon'),
			e('🎁', 'wrapped gift', 'hadiah kado')
		]
	},
	{
		id: 'animals',
		icon: '🐶',
		emojis: [
			e('🐶', 'dog face', 'anjing'),
			e('🐱', 'cat face', 'kucing'),
			e('🐭', 'mouse face', 'tikus'),
			e('🐹', 'hamster'),
			e('🐰', 'rabbit face', 'kelinci'),
			e('🦊', 'fox'),
			e('🐻', 'bear', 'beruang'),
			e('🐼', 'panda'),
			e('🐨', 'koala'),
			e('🐯', 'tiger face', 'macan'),
			e('🦁', 'lion', 'singa'),
			e('🐮', 'cow face', 'sapi'),
			e('🐷', 'pig face', 'babi'),
			e('🐸', 'frog', 'katak'),
			e('🐵', 'monkey face', 'monyet'),
			e('🙈', 'see no evil monkey'),
			e('🙉', 'hear no evil monkey'),
			e('🙊', 'speak no evil monkey'),
			e('🐔', 'chicken', 'ayam'),
			e('🐧', 'penguin'),
			e('🐦', 'bird', 'burung'),
			e('🦆', 'duck', 'bebek'),
			e('🦅', 'eagle', 'elang'),
			e('🦉', 'owl', 'burung hantu'),
			e('🦄', 'unicorn'),
			e('🐝', 'honeybee', 'lebah'),
			e('🦋', 'butterfly', 'kupu kupu'),
			e('🐌', 'snail', 'siput'),
			e('🐞', 'lady beetle', 'kepik'),
			e('🐢', 'turtle', 'kura kura'),
			e('🐍', 'snake', 'ular'),
			e('🐙', 'octopus', 'gurita'),
			e('🦀', 'crab', 'kepiting'),
			e('🐠', 'tropical fish', 'ikan'),
			e('🐬', 'dolphin', 'lumba lumba'),
			e('🐳', 'spouting whale', 'paus'),
			e('🦈', 'shark', 'hiu'),
			e('🐊', 'crocodile', 'buaya'),
			e('🐘', 'elephant', 'gajah'),
			e('🦒', 'giraffe', 'jerapah'),
			e('🐕', 'dog', 'anjing'),
			e('🐈', 'cat', 'kucing'),
			e('🌸', 'cherry blossom', 'sakura'),
			e('🌹', 'rose', 'mawar'),
			e('🌻', 'sunflower', 'bunga matahari'),
			e('🌷', 'tulip'),
			e('🌺', 'hibiscus'),
			e('🍀', 'four leaf clover', 'keberuntungan'),
			e('🌿', 'herb', 'daun'),
			e('🌵', 'cactus', 'kaktus'),
			e('🌴', 'palm tree', 'pohon'),
			e('🌙', 'crescent moon', 'bulan'),
			e('☀️', 'sun', 'matahari'),
			e('🌈', 'rainbow', 'pelangi'),
			e('☁️', 'cloud', 'awan'),
			e('🌧️', 'rain cloud', 'hujan'),
			e('❄️', 'snowflake', 'salju'),
			e('⚡', 'high voltage', 'petir'),
			e('🌊', 'water wave', 'laut')
		]
	},
	{
		id: 'food',
		icon: '🍔',
		emojis: [
			e('🍏', 'green apple'),
			e('🍎', 'red apple', 'apel'),
			e('🍊', 'tangerine', 'jeruk'),
			e('🍋', 'lemon'),
			e('🍌', 'banana', 'pisang'),
			e('🍉', 'watermelon', 'semangka'),
			e('🍇', 'grapes', 'anggur'),
			e('🍓', 'strawberry', 'stroberi'),
			e('🍒', 'cherries', 'ceri'),
			e('🍑', 'peach'),
			e('🥭', 'mango', 'mangga'),
			e('🍍', 'pineapple', 'nanas'),
			e('🥥', 'coconut', 'kelapa'),
			e('🥝', 'kiwi'),
			e('🍅', 'tomato', 'tomat'),
			e('🥑', 'avocado', 'alpukat'),
			e('🥦', 'broccoli', 'brokoli'),
			e('🥕', 'carrot', 'wortel'),
			e('🌽', 'corn', 'jagung'),
			e('🌶️', 'hot pepper', 'cabai'),
			e('🥒', 'cucumber', 'timun'),
			e('🥔', 'potato', 'kentang'),
			e('🍞', 'bread', 'roti'),
			e('🥐', 'croissant'),
			e('🧀', 'cheese', 'keju'),
			e('🥚', 'egg', 'telur'),
			e('🍳', 'cooking', 'memasak'),
			e('🥞', 'pancakes'),
			e('🍗', 'poultry leg', 'ayam'),
			e('🍖', 'meat on bone', 'daging'),
			e('🍔', 'hamburger', 'burger'),
			e('🍟', 'french fries', 'kentang goreng'),
			e('🍕', 'pizza'),
			e('🌮', 'taco'),
			e('🥗', 'green salad', 'salad'),
			e('🍝', 'spaghetti', 'pasta'),
			e('🍜', 'steaming bowl', 'mie ramen'),
			e('🍲', 'pot of food', 'sup'),
			e('🍛', 'curry rice', 'kari'),
			e('🍣', 'sushi'),
			e('🍱', 'bento box'),
			e('🍤', 'fried shrimp', 'udang'),
			e('🍙', 'rice ball', 'nasi'),
			e('🍡', 'dango'),
			e('🍦', 'soft ice cream', 'es krim'),
			e('🍰', 'shortcake', 'kue'),
			e('🎂', 'birthday cake', 'kue ulang tahun'),
			e('🍫', 'chocolate bar', 'cokelat'),
			e('🍬', 'candy', 'permen'),
			e('🍿', 'popcorn'),
			e('🍩', 'doughnut', 'donat'),
			e('🍪', 'cookie', 'biskuit'),
			e('🥜', 'peanuts', 'kacang'),
			e('🍯', 'honey pot', 'madu'),
			e('🥛', 'glass of milk', 'susu'),
			e('🍼', 'baby bottle'),
			e('☕', 'hot beverage', 'kopi teh'),
			e('🍵', 'teacup without handle', 'teh'),
			e('🧃', 'beverage box'),
			e('🥤', 'cup with straw', 'minuman'),
			e('🍺', 'beer mug', 'bir'),
			e('🥂', 'clinking glasses', 'bersulang'),
			e('🍷', 'wine glass', 'anggur'),
			e('🍹', 'tropical drink'),
			e('🍾', 'bottle with popping cork')
		]
	},
	{
		id: 'activities',
		icon: '⚽',
		emojis: [
			e('⚽', 'soccer ball', 'bola'),
			e('🏀', 'basketball', 'bola basket'),
			e('🏈', 'american football'),
			e('⚾', 'baseball'),
			e('🎾', 'tennis'),
			e('🏐', 'volleyball', 'voli'),
			e('🏓', 'ping pong', 'tenis meja'),
			e('🏸', 'badminton', 'bulu tangkis'),
			e('🏒', 'ice hockey'),
			e('🥊', 'boxing glove', 'tinju'),
			e('🥋', 'martial arts uniform', 'karate'),
			e('⛸️', 'ice skate', 'sepatu es'),
			e('🎿', 'skis', 'ski'),
			e('🏋️', 'person lifting weights', 'angkat beban'),
			e('🤸', 'cartwheeling', 'senam'),
			e('🏌️', 'person golfing', 'golf'),
			e('🧘', 'person in lotus position', 'yoga meditasi'),
			e('🏄', 'person surfing', 'selancar'),
			e('🏊', 'person swimming', 'berenang'),
			e('🚴', 'person biking', 'sepeda'),
			e('🧗', 'person climbing', 'panjat'),
			e('🏆', 'trophy', 'piala juara'),
			e('🥇', 'gold medal', 'medali emas'),
			e('🥈', 'silver medal', 'medali perak'),
			e('🥉', 'bronze medal', 'medali perunggu'),
			e('🎗️', 'reminder ribbon'),
			e('🎫', 'ticket', 'tiket'),
			e('🎭', 'performing arts', 'teater'),
			e('🎨', 'artist palette', 'seni lukis'),
			e('🎬', 'clapper board', 'film'),
			e('🎤', 'microphone', 'mikrofon'),
			e('🎧', 'headphone', 'headset'),
			e('🎼', 'musical score', 'partitur'),
			e('🎹', 'musical keyboard', 'piano'),
			e('🥁', 'drum', 'drum'),
			e('🎷', 'saxophone'),
			e('🎺', 'trumpet', 'terompet'),
			e('🎸', 'guitar', 'gitar'),
			e('🎻', 'violin', 'biola'),
			e('🎲', 'game die', 'dadu'),
			e('🎯', 'direct hit', 'target'),
			e('🎮', 'video game', 'game'),
			e('🧩', 'puzzle piece', 'puzzle'),
			e('🎪', 'circus tent'),
			e('🎡', 'ferris wheel', 'bianglala')
		]
	},
	{
		id: 'travel',
		icon: '✈️',
		emojis: [
			e('✈️', 'airplane', 'pesawat'),
			e('🛫', 'airplane departure', 'berangkat'),
			e('🛬', 'airplane arrival', 'mendarat'),
			e('🚀', 'rocket', 'roket'),
			e('🛸', 'flying saucer', 'ufo'),
			e('🚁', 'helicopter', 'helikopter'),
			e('🚗', 'car', 'mobil'),
			e('🚕', 'taxi', 'taksi'),
			e('🚌', 'bus'),
			e('🚓', 'police car', 'polisi'),
			e('🚑', 'ambulance', 'ambulans'),
			e('🚒', 'fire engine', 'pemadam'),
			e('🚚', 'delivery truck', 'truk'),
			e('🏍️', 'motorcycle', 'motor'),
			e('🛵', 'motor scooter', 'skuter'),
			e('🚲', 'bicycle', 'sepeda'),
			e('🛴', 'kick scooter'),
			e('🚂', 'locomotive', 'kereta'),
			e('🚄', 'high speed train', 'kereta cepat'),
			e('🚇', 'metro', 'mrt'),
			e('🚉', 'station', 'stasiun'),
			e('⛵', 'sailboat', 'perahu'),
			e('🚤', 'speedboat'),
			e('🚢', 'ship', 'kapal'),
			e('⚓', 'anchor', 'jangkar'),
			e('🗺️', 'world map', 'peta'),
			e('🗿', 'moai'),
			e('🗽', 'statue of liberty'),
			e('🗼', 'tokyo tower'),
			e('🏰', 'castle', 'kastil'),
			e('🏯', 'japanese castle'),
			e('⛩️', 'shinto shrine', 'kuil'),
			e('🏟️', 'stadium', 'stadion'),
			e('🎢', 'roller coaster'),
			e('⛲', 'fountain', 'air mancur'),
			e('🏖️', 'beach with umbrella', 'pantai'),
			e('🏝️', 'desert island', 'pulau'),
			e('🌋', 'volcano', 'gunung berapi'),
			e('⛰️', 'mountain', 'gunung'),
			e('🗻', 'mount fuji'),
			e('🏕️', 'camping', 'berkemah'),
			e('🏠', 'house', 'rumah'),
			e('🏢', 'office building', 'kantor'),
			e('🏬', 'department store', 'mall'),
			e('🏥', 'hospital', 'rumah sakit'),
			e('🏦', 'bank'),
			e('🏨', 'hotel'),
			e('🏫', 'school', 'sekolah'),
			e('💒', 'wedding', 'pernikahan'),
			e('🌅', 'sunrise', 'matahari terbit'),
			e('🌄', 'sunrise over mountains'),
			e('🌃', 'night with stars', 'malam'),
			e('🎆', 'fireworks', 'kembang api'),
			e('🌉', 'bridge at night', 'jembatan')
		]
	},
	{
		id: 'objects',
		icon: '💡',
		emojis: [
			e('⌚', 'watch', 'jam tangan'),
			e('📱', 'mobile phone', 'ponsel'),
			e('💻', 'laptop', 'komputer'),
			e('⌨️', 'keyboard'),
			e('🖥️', 'desktop computer'),
			e('🖱️', 'computer mouse'),
			e('💾', 'floppy disk', 'disket'),
			e('💿', 'optical disk', 'cd'),
			e('📷', 'camera', 'kamera'),
			e('📸', 'camera with flash', 'foto'),
			e('📹', 'video camera'),
			e('🎥', 'movie camera', 'kamera film'),
			e('📺', 'television', 'tv'),
			e('📻', 'radio'),
			e('🎙️', 'studio microphone'),
			e('⏰', 'alarm clock', 'jam weker'),
			e('⏳', 'hourglass not done', 'waktu'),
			e('📡', 'satellite antenna', 'antena'),
			e('🔋', 'battery', 'baterai'),
			e('🔌', 'electric plug', 'colokan'),
			e('💡', 'light bulb', 'ide lampu'),
			e('🔦', 'flashlight', 'senter'),
			e('🕯️', 'candle', 'lilin'),
			e('💸', 'money with wings', 'uang'),
			e('💵', 'dollar banknote', 'uang'),
			e('💰', 'money bag', 'uang'),
			e('💳', 'credit card', 'kartu kredit'),
			e('💎', 'gem stone', 'permata'),
			e('⚖️', 'balance scale', 'timbangan'),
			e('🔧', 'wrench', 'kunci inggris'),
			e('🔨', 'hammer', 'palu'),
			e('🛠️', 'hammer and wrench', 'perkakas'),
			e('⚙️', 'gear', 'gir'),
			e('🧲', 'magnet'),
			e('🔫', 'water pistol', 'pistol'),
			e('💣', 'bomb', 'bom'),
			e('🧨', 'firecracker', 'petasan'),
			e('🔪', 'kitchen knife', 'pisau'),
			e('🛡️', 'shield', 'perisai'),
			e('🔮', 'crystal ball', 'bola kristal'),
			e('🔭', 'telescope', 'teleskop'),
			e('🔬', 'microscope', 'mikroskop'),
			e('💊', 'pill', 'obat'),
			e('💉', 'syringe', 'suntik'),
			e('🩺', 'stethoscope'),
			e('🧪', 'test tube', 'tabung reaksi'),
			e('🚽', 'toilet'),
			e('🛁', 'bathtub', 'bak mandi'),
			e('🚪', 'door', 'pintu'),
			e('🛏️', 'bed', 'kasur'),
			e('🛋️', 'couch and lamp', 'sofa'),
			e('🪑', 'chair', 'kursi'),
			e('🗝️', 'old key', 'kunci'),
			e('🔑', 'key', 'kunci'),
			e('🧳', 'luggage', 'koper'),
			e('🎀', 'ribbon', 'pita'),
			e('🧣', 'scarf', 'syal'),
			e('🧤', 'gloves', 'sarung tangan'),
			e('🕶️', 'sunglasses', 'kacamata'),
			e('👕', 't-shirt', 'kaos'),
			e('👗', 'dress', 'gaun'),
			e('👠', 'high-heeled shoe', 'sepatu'),
			e('👟', 'running shoe', 'sepatu olahraga'),
			e('🎒', 'backpack', 'tas'),
			e('👜', 'handbag', 'tas'),
			e('📚', 'books', 'buku'),
			e('📖', 'open book', 'buku'),
			e('📝', 'memo', 'catatan'),
			e('📰', 'newspaper', 'koran'),
			e('📅', 'calendar', 'kalender'),
			e('📌', 'pushpin', 'paku'),
			e('📎', 'paperclip', 'klip'),
			e('✂️', 'scissors', 'gunting'),
			e('📦', 'package', 'paket'),
			e('✉️', 'envelope', 'surat'),
			e('🏷️', 'label', 'label')
		]
	},
	{
		id: 'symbols',
		icon: '✅',
		emojis: [
			e('✅', 'check mark button', 'benar centang'),
			e('❌', 'cross mark', 'salah silang'),
			e('❎', 'cross mark button'),
			e('➕', 'plus', 'tambah'),
			e('➖', 'minus', 'kurang'),
			e('➗', 'divide', 'bagi'),
			e('✖️', 'multiply', 'kali'),
			e('♾️', 'infinity', 'tak hingga'),
			e('💲', 'heavy dollar sign'),
			e('❓', 'question mark', 'tanya'),
			e('❔', 'white question mark'),
			e('❗', 'exclamation mark', 'seru'),
			e('❕', 'white exclamation mark'),
			e('‼️', 'double exclamation mark'),
			e('⁉️', 'exclamation question mark'),
			e('🔟', 'keycap ten', 'sepuluh'),
			e('🔠', 'input latin uppercase'),
			e('🔢', 'input numbers', 'angka'),
			e('#️⃣', 'keycap number sign', 'tagar'),
			e('1️⃣', 'keycap one'),
			e('2️⃣', 'keycap two'),
			e('3️⃣', 'keycap three'),
			e('🔔', 'bell', 'lonceng'),
			e('🔕', 'bell with slash', 'diam'),
			e('🔒', 'locked', 'terkunci'),
			e('🔓', 'unlocked', 'terbuka'),
			e('🔗', 'link', 'tautan'),
			e('🔄', 'counterclockwise arrows', 'muat ulang'),
			e('▶️', 'play button', 'putar'),
			e('⏸️', 'pause button', 'jeda'),
			e('⏹️', 'stop button', 'berhenti'),
			e('⏭️', 'next track', 'berikutnya'),
			e('⏮️', 'last track', 'sebelumnya'),
			e('⬆️', 'up arrow', 'atas'),
			e('⬇️', 'down arrow', 'bawah'),
			e('⬅️', 'left arrow', 'kiri'),
			e('➡️', 'right arrow', 'kanan'),
			e('↗️', 'up-right arrow'),
			e('↘️', 'down-right arrow'),
			e('🔀', 'shuffle', 'acak'),
			e('🔁', 'repeat', 'ulang'),
			e('🔊', 'speaker high volume', 'suara'),
			e('🔇', 'muted speaker', 'bisu'),
			e('🎵', 'musical note', 'nada'),
			e('🎶', 'musical notes', 'musik'),
			e('♻️', 'recycling symbol', 'daur ulang'),
			e('🔱', 'trident emblem'),
			e('📶', 'antenna bars', 'sinyal'),
			e('📳', 'vibration mode', 'getar'),
			e('🆗', 'OK button', 'oke'),
			e('🆒', 'cool button', 'keren'),
			e('🆕', 'new button', 'baru'),
			e('🆓', 'free button', 'gratis'),
			e('🔞', 'no one under eighteen'),
			e('⚠️', 'warning', 'peringatan'),
			e('🚫', 'prohibited', 'dilarang'),
			e('⛔', 'no entry', 'dilarang masuk'),
			e('💤', 'zzz', 'tidur')
		]
	}
];

/** localStorage key holding the recently used emoji (newest first). */
export const EMOJI_RECENT_KEY = 'page48:emoji:recent';
export const EMOJI_RECENT_LIMIT = 16;

/** Search across every category by label and aliases. */
export function searchEmojis(query: string): Emoji[] {
	const q = query.trim().toLowerCase();
	if (!q) return [];

	const found = EMOJI_CATEGORIES.flatMap((category) => category.emojis).filter((emoji) => {
		const haystack = `${emoji.label} ${emoji.aliases ?? ''}`.toLowerCase();
		return haystack.includes(q);
	});

	// Results are rendered in one keyed list, so keep a single entry per glyph.
	return [...new Map(found.map((emoji) => [emoji.char, emoji])).values()];
}
