class Info:
    POST_CREATED = "Post created successfully."
    POST_UPDATED = "Post updated successfully."
    POST_DELETED = "Post deleted successfully."
    LIKE_TOGGLED = "Like status toggled."
    REPOST_TOGGLED = "Repost status toggled."
    BOOKMARK_TOGGLED = "Bookmark status toggled."
    REPORT_CREATED = "Report submitted successfully."
    VIDEO_UPLOADED = "Video uploaded successfully."

class ErrorCode:
    POST_NOT_FOUND = "Post not found."
    POST_CREATE_ERROR = "Failed to create post."
    UNAUTHORIZED_ACTION = "You are not authorized to perform this action."
    MAX_MEDIA_EXCEEDED = "Maximum number of media allowed per post is 4."
    REPLY_NOT_FOUND = "The post you are trying to reply to does not exist."
    USER_NOT_FOUND = "User not found."
    REPORT_CREATE_ERROR = "Failed to submit report."
    CANNOT_REPORT_SELF = "You cannot report yourself."
    REPORT_ALREADY_EXISTS = "You have already reported this."
    INVALID_REPORT_TARGET = "The reported target does not exist."
    VIDEO_UPLOAD_ERROR = "Failed to upload video."
    VIDEO_TOO_LARGE = "Video exceeds the maximum size of 50MB."
    INVALID_VIDEO_TYPE = "Unsupported video format. Allowed: MP4 or WebM."
    MAX_VIDEO_EXCEEDED = "Maximum number of videos allowed per post is 1."
    INVALID_MEDIA_COMBINATION = "A post cannot contain both images and a video."
    INVALID_VIDEO = "The video reference is invalid."

class DomainErrorCode:
    POST_NOT_FOUND = "Post not found."
    POST_CREATION_FAILED = "Failed to create post."
    UNAUTHORIZED = "Unauthorized."
    USER_NOT_FOUND = "User not found."
    REPORT_CREATION_FAILED = "Failed to submit report."
    CANNOT_REPORT_SELF = "You cannot report yourself."
    REPORT_ALREADY_EXISTS = "You have already reported this."
    INVALID_REPORT_TARGET = "The reported target does not exist."
    VIDEO_UPLOAD_FAILED = "Failed to upload video."
    VIDEO_TOO_LARGE = "Video exceeds the maximum size of 50MB."
    INVALID_VIDEO_TYPE = "Unsupported video format. Allowed: MP4 or WebM."
    MAX_VIDEO_EXCEEDED = "Maximum number of videos allowed per post is 1."
    INVALID_MEDIA_COMBINATION = "A post cannot contain both images and a video."
    INVALID_VIDEO = "The video reference is invalid."
