class Info:
    MEMBER_FOUND = "Member found successfully."
    MEMBERS_RETRIEVED = "Members retrieved successfully."
    MEMBER_DATA_SEEDED = "Member data seeded successfully."


class ErrorCode:
    MEMBER_NOT_FOUND = "Member not found."
    MEMBER_FETCH_ERROR = "Failed to fetch member data."


class DomainErrorCode:
    MEMBER_NOT_FOUND = "Member not found."
    MEMBER_FETCH_FAILED = "Failed to fetch member data."

# JKT48 Active Members Data with Generation and Jiko
class Jkt48Members:
    data = [
        {
            "id": 76,
            "name": "Feni Fitriyanti",
            "href": "https://jkt48.com/member/detail/id/76?lang=id",
            "img": "https://jkt48.com/profile/feni_fitriyanti.jpg?v=20230116",
            "birthdate": "16 Januari 1999",
            "bloodType": "O",
            "horoscope": "Capricorn",
            "height": "162cm",
            "nickname": "Feni",
            "generation": "3",
            "jiko": "Matahari yang indah, yang akan memberikan kehangatan di setiap harinya. Halo aku Feni.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/F_FeniJKT48",
                "instagram": "https://www.instagram.com/jkt48feni/",
                "tiktok": "https://www.tiktok.com/@fenijkt48/",
                "threads": "https://www.threads.net/@jkt48feni",
                "showroom": "https://www.showroom-live.com/JKT48_Feni",
                "idn_app": "https://www.idn.app/jkt48_feni",
            },
        },
        {
            "id": 190,
            "name": "Gita Sekar Andarini",
            "href": "https://jkt48.com/member/detail/id/190?lang=id",
            "img": "https://jkt48.com/profile/gita_sekar_andarini.jpg?v=20230116",
            "birthdate": "30 Juni 2001",
            "bloodType": "O",
            "horoscope": "Cancer",
            "height": "165cm",
            "nickname": "Gita",
            "generation": "7",
            "jiko": "Diam bukan berarti tidak memperhatikanmu, aku Gita!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/A_GitaJKT48",
                "instagram": "https://www.instagram.com/jkt48gita/",
                "tiktok": "https://www.tiktok.com/@gitajkt48/",
                "threads": "https://www.threads.net/@jkt48gita",
                "showroom": "https://www.showroom-live.com/JKT48_Gita",
                "idn_app": "https://www.idn.app/jkt48_gita",
            },
        },
        {
            "id": 199,
            "name": "Mutiara Azzahra",
            "href": "https://jkt48.com/member/detail/id/199?lang=id",
            "img": "https://jkt48.com/profile/mutiara_azzahra.jpg?v=20230116",
            "birthdate": "12 Juli 2004",
            "bloodType": "B",
            "horoscope": "Cancer",
            "height": "158cm",
            "nickname": "Muthe",
            "generation": "7",
            "jiko": "Tok tok! Siapa? Si penari yang akan menarikmu ke duniaku.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/A_MutheJKT48",
                "instagram": "https://www.instagram.com/jkt48.muthe_/",
                "tiktok": "https://www.tiktok.com/@muthejkt48/",
                "threads": "https://www.threads.net/@jkt48.muthe_",
                "showroom": "https://www.showroom-live.com/JKT48_Muthe",
                "idn_app": "https://www.idn.app/jkt48_muthe",
            },
        },
        {
            "id": 204,
            "name": "Angelina Christy",
            "href": "https://jkt48.com/member/detail/id/204?lang=id",
            "img": "https://jkt48.com/profile/angelina_christy.jpg?v=20230116",
            "birthdate": "5 Desember 2005",
            "bloodType": "O",
            "horoscope": "Sagitarius",
            "height": "163cm",
            "nickname": "Christy",
            "generation": "7",
            "jiko": "Peduli dan berbaik hati, siapa dia? Chriiiis-ty!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/A_ChristyJKT48",
                "instagram": "https://www.instagram.com/jkt48.christy/",
                "tiktok": "https://www.tiktok.com/@christyjkt48/",
                "threads": "https://www.threads.net/@jkt48.christy",
                "showroom": "https://www.showroom-live.com/JKT48_Christy",
                "idn_app": "https://www.idn.app/jkt48_christy",
            },
        },
        {
            "id": 210,
            "name": "Helisma Putri",
            "href": "https://jkt48.com/member/detail/id/210?lang=id",
            "img": "https://jkt48.com/profile/helisma_putri.jpg?v=20230116",
            "birthdate": "15 Juni 2000",
            "bloodType": "A",
            "horoscope": "Gemini",
            "height": "165cm",
            "nickname": "Eli",
            "generation": "7",
            "jiko": "Dengan energi kegembiraanku, aku akan menghangatkan suasana. Halo halo, aku Ceu Eli!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/H_EliJKT48",
                "instagram": "https://www.instagram.com/jkt48.eli/",
                "tiktok": "https://www.tiktok.com/@elijkt48/",
                "threads": "https://www.threads.net/@jkt48.eli",
                "showroom": "https://www.showroom-live.com/JKT48_Eli",
                "idn_app": "https://www.idn.app/jkt48_eli",
            },
        },
        {
            "id": 213,
            "name": "Febriola Sinambela",
            "href": "https://jkt48.com/member/detail/id/213?lang=id",
            "img": "https://jkt48.com/profile/febriola_sinambela.jpg?v=20230116",
            "birthdate": "26 Februari 2005",
            "bloodType": "B",
            "horoscope": "Pisces",
            "height": "154cm",
            "nickname": "Olla",
            "generation": "7",
            "jiko": "Dengan keajaibanku, aku akan membuat kalian selalu tertawa. Halo, aku Olla, si mechanic girl!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/F_OllaJKT48",
                "instagram": "https://www.instagram.com/jkt48.olla/",
                "tiktok": "https://www.tiktok.com/@ollajkt48/",
                "threads": "https://www.threads.net/@jkt48.olla",
                "showroom": "https://www.showroom-live.com/JKT48_Olla",
                "idn_app": "https://www.idn.app/jkt48_olla",
            },
        },
        {
            "id": 214,
            "name": "Freya Jayawardana",
            "href": "https://jkt48.com/member/detail/id/214?lang=id",
            "img": "https://jkt48.com/profile/freya_jayawardana.jpg?v=20230116",
            "birthdate": "13 Februari 2006",
            "bloodType": "B",
            "horoscope": "Aquarius",
            "height": "154cm",
            "nickname": "Freya",
            "generation": "7",
            "jiko": "Gadis koleris yang suka berimajinasi, terangi harimu dengan senyum karamelku. Halo semua, aku Freya!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Freya_JKT48",
                "instagram": "https://www.instagram.com/jkt48.freya/",
                "tiktok": "https://www.tiktok.com/@freyajkt48/",
                "threads": "https://www.threads.net/@jkt48.freya",
                "showroom": "https://www.showroom-live.com/JKT48_Freya",
                "idn_app": "https://www.idn.app/jkt48_freya",
            },
        },
        {
            "id": 215,
            "name": "Jessica Chandra",
            "href": "https://jkt48.com/member/detail/id/215?lang=id",
            "img": "https://jkt48.com/profile/jessica_chandra.jpg?v=20230116",
            "birthdate": "23 September 2005",
            "bloodType": "O",
            "horoscope": "Libra",
            "height": "163cm",
            "nickname": "Jessi",
            "generation": "7",
            "jiko": "Suka menari dan akan selalu berusaha menjadi sumber energimu. Hai, aku Jessi!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/C_JessiJKT48",
                "instagram": "https://www.instagram.com/jkt48.jessi/",
                "tiktok": "https://www.tiktok.com/@jessijkt48/",
                "threads": "https://www.threads.net/@jkt48.jessi",
                "showroom": "https://www.showroom-live.com/JKT48_Jessi",
                "idn_app": "https://www.idn.app/jkt48_jessi",
            },
        },
        {
            "id": 221,
            "name": "Cornelia Vanisa",
            "href": "https://jkt48.com/member/detail/id/221?lang=id",
            "img": "https://jkt48.com/profile/cornelia_vanisa.jpg?v=20230116",
            "birthdate": "26 Juli 2002",
            "bloodType": "O",
            "horoscope": "Leo",
            "height": "162cm",
            "nickname": "Oniel",
            "generation": "8",
            "jiko": "Si pelawak dengan jokes bapak-bapak yang akan menghiburmu. Halo, aku Oniel!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/C_OnielJKT48",
                "instagram": "https://www.instagram.com/jkt48.oniel/",
                "tiktok": "https://www.tiktok.com/@onieljkt48/",
                "threads": "https://www.threads.net/@jkt48.oniel",
                "showroom": "https://www.showroom-live.com/JKT48_Oniel",
                "idn_app": "https://www.idn.app/jkt48_oniel",
            },
        },
        {
            "id": 223,
            "name": "Fiony Alveria",
            "href": "https://jkt48.com/member/detail/id/223?lang=id",
            "img": "https://jkt48.com/profile/fiony_alveria.jpg?v=20230116",
            "birthdate": "4 Februari 2002",
            "bloodType": "O",
            "horoscope": "Aquarius",
            "height": "158cm",
            "nickname": "Fiony",
            "generation": "8",
            "jiko": "Seperti simfoni yang menenangkan hati. Halo aku Fiony!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/A_FionyJKT48",
                "instagram": "https://www.instagram.com/jkt48.fiony/",
                "tiktok": "https://www.tiktok.com/@fionyjkt48/",
                "threads": "https://www.threads.net/@jkt48.fiony",
                "showroom": "https://www.showroom-live.com/JKT48_Fiony",
                "idn_app": "https://www.idn.app/jkt48_fiony",
            },
        },
        {
            "id": 228,
            "name": "Lulu Salsabila",
            "href": "https://jkt48.com/member/detail/id/228?lang=id",
            "img": "https://jkt48.com/profile/lulu_salsabila.jpg?v=20230116",
            "birthdate": "23 Oktober 2002",
            "bloodType": "B",
            "horoscope": "Scorpio",
            "height": "157cm",
            "nickname": "Lulu",
            "generation": "8",
            "jiko": "Terang seperti bulan, bersinar seperti bintang.. Aku Lulu!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/A_LuluJKT48",
                "instagram": "https://www.instagram.com/jkt48.lulu/",
                "tiktok": "https://www.tiktok.com/@lulu_jkt48/",
                "threads": "https://www.threads.net/@jkt48.lulu",
                "showroom": "https://www.showroom-live.com/JKT48_Lulu",
                "idn_app": "https://www.idn.app/jkt48_lulu",
            },
        },
        {
            "id": 241,
            "name": "Indah Cahya",
            "href": "https://jkt48.com/member/detail/id/241?lang=id",
            "img": "https://jkt48.com/profile/indah_cahya.jpg?v=20230116",
            "birthdate": "20 Maret 2001",
            "bloodType": "A",
            "horoscope": "Pisces",
            "height": "165cm",
            "nickname": "Indah",
            "generation": "9",
            "jiko": "Tak banyak bicara, bercerita melalui tulisan. Hai aku Indah.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/C_IndahJKT48",
                "instagram": "https://www.instagram.com/jkt48indah_/",
                "tiktok": "https://www.tiktok.com/@indahjkt48/",
                "threads": "https://www.threads.net/@jkt48indah_",
                "showroom": "https://www.showroom-live.com/JKT48_Indah",
                "idn_app": "https://www.idn.app/jkt48_indah",
            },
        },
        {
            "id": 242,
            "name": "Kathrina Irene",
            "href": "https://jkt48.com/member/detail/id/242?lang=id",
            "img": "https://jkt48.com/profile/kathrina_irene.jpg?v=20230116",
            "birthdate": "26 Juli 2006",
            "bloodType": "A",
            "horoscope": "Leo",
            "height": "165cm",
            "nickname": "Kathrina",
            "generation": "9",
            "jiko": "Never miss a chance to be a star. Halo, aku Kathrina!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/I_KathrinaJKT48",
                "instagram": "https://www.instagram.com/jkt48.kathrina/",
                "tiktok": "https://www.tiktok.com/@kathrinjkt48/",
                "threads": "https://www.threads.net/@jkt48.kathrina",
                "showroom": "https://www.showroom-live.com/JKT48_Kathrina",
                "idn_app": "https://www.idn.app/jkt48_kathrina",
            },
        },
        {
            "id": 243,
            "name": "Marsha Lenathea",
            "href": "https://jkt48.com/member/detail/id/243?lang=id",
            "img": "https://jkt48.com/profile/marsha_lenathea.jpg?v=20230116",
            "birthdate": "9 Januari 2006",
            "bloodType": "O",
            "horoscope": "Capricorn",
            "height": "163cm",
            "nickname": "Marsha",
            "generation": "9",
            "jiko": "Seperti piza yang dinanti-nantikan semua orang, selalu nantikan aku, ya! Halo, aku Marsha!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/L_MarshaJKT48",
                "instagram": "https://www.instagram.com/jkt48.marsha/",
                "tiktok": "https://www.tiktok.com/@marsha.jkt48/",
                "threads": "https://www.threads.net/@jkt48.marsha",
                "showroom": "https://www.showroom-live.com/JKT48_Marsha",
                "idn_app": "https://www.idn.app/jkt48_marsha",
            },
        },
        {
            "id": 249,
            "name": "Amanda Sukma",
            "href": "https://jkt48.com/member/detail/id/249?lang=id",
            "img": "https://jkt48.com/profile/amanda_sukma.jpg?v=20230530",
            "birthdate": "17 Desember 2004",
            "bloodType": "O",
            "horoscope": "Sagitarius",
            "height": "160cm",
            "nickname": "Amanda",
            "generation": "10",
            "jiko": "Aku akan membuat hatimu berdebar kencang... Halo, aku Amanda!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/PS_AmandaJKT48",
                "instagram": "https://www.instagram.com/jkt48.amanda.s/",
                "tiktok": "https://www.tiktok.com/@jkt48.amanda.s/",
                "threads": "https://www.threads.net/@jkt48.amanda.s",
                "showroom": "https://www.showroom-live.com/JKT48_Amanda",
                "idn_app": "https://www.idn.app/jkt48_amanda",
            },
        },
        {
            "id": 250,
            "name": "Aurellia",
            "href": "https://jkt48.com/member/detail/id/250?lang=id",
            "img": "https://jkt48.com/profile/aurellia.jpg?v=20230531",
            "birthdate": "29 Oktober 2002",
            "bloodType": "O",
            "horoscope": "Scorpio",
            "height": "155cm",
            "nickname": "Lia",
            "generation": "10",
            "jiko": "Si social butterfly yang energik dan periang! Halo aku Aurellia.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/AU_LiaJKT48",
                "instagram": "https://www.instagram.com/jkt48.aurellia_/",
                "tiktok": "https://www.tiktok.com/@jkt48.aurellia_/",
                "threads": "https://www.threads.net/@jkt48.aurellia_",
                "showroom": "https://www.showroom-live.com/JKT48_Aurellia",
                "idn_app": "https://www.idn.app/jkt48_aurellia",
            },
        },
        {
            "id": 252,
            "name": "Gabriela Abigail",
            "href": "https://jkt48.com/member/detail/id/252?lang=id",
            "img": "https://jkt48.com/profile/gabriela_abigail.jpg?v=20230531",
            "birthdate": "7 Agustus 2006",
            "bloodType": "B",
            "horoscope": "Leo",
            "height": "160cm",
            "nickname": "Ella",
            "generation": "10",
            "jiko": "Ohayo! Konnichiwa! Oyasumi! Aku ingin ada di setiap harimu. Halo semuanya aku Ella.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/AM_EllaJKT48",
                "instagram": "https://www.instagram.com/jkt48.ella.a/",
                "tiktok": "https://www.tiktok.com/@jkt48.ella.a/",
                "threads": "https://www.threads.net/@jkt48.ella.a",
                "showroom": "https://www.showroom-live.com/JKT48_Ella",
                "idn_app": "https://www.idn.app/jkt48_ella",
            },
        },
        {
            "id": 253,
            "name": "Indira Seruni",
            "href": "https://jkt48.com/member/detail/id/253?lang=id",
            "img": "https://jkt48.com/profile/indira_seruni.jpg?v=20230531",
            "birthdate": "26 April 2004",
            "bloodType": "A",
            "horoscope": "Taurus",
            "height": "160cm",
            "nickname": "Indira",
            "generation": "10",
            "jiko": "Senyumanku menatap lurus ke arahmu, smiley eyes. Halo aku Indira.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/SP_IndiraJKT48",
                "instagram": "https://www.instagram.com/jkt48.indira.s/",
                "tiktok": "https://www.tiktok.com/@jkt48.indira.s/",
                "threads": "https://www.threads.net/@jkt48.indira.s",
                "showroom": "https://www.showroom-live.com/JKT48_Indira",
                "idn_app": "https://www.idn.app/jkt48_indira",
            },
        },
        {
            "id": 254,
            "name": "Jesslyn Elly",
            "href": "https://jkt48.com/member/detail/id/254?lang=id",
            "img": "https://jkt48.com/profile/jesslyn_elly.jpg?v=20230531",
            "birthdate": "13 September 2001",
            "bloodType": "O",
            "horoscope": "Virgo",
            "height": "155cm",
            "nickname": "Lyn",
            "generation": "10",
            "jiko": "Seperti ombak laut yang tenang, tiba-tiba aku akan menyapumu dengan banyak cinta. Halo aku Lyn.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/SE_LynJKT48",
                "instagram": "https://www.instagram.com/jkt48.lyn.s/",
                "tiktok": "https://www.tiktok.com/@jkt48.lyn.s/",
                "threads": "https://www.threads.net/@jkt48.lyn.s",
                "showroom": "https://www.showroom-live.com/JKT48_Lyn",
                "idn_app": "https://www.idn.app/jkt48_lyn",
            },
        },
        {
            "id": 255,
            "name": "Raisha Syifa",
            "href": "https://jkt48.com/member/detail/id/255?lang=id",
            "img": "https://jkt48.com/profile/raisha_syifa.jpg?v=20230530",
            "birthdate": "11 November 2007",
            "bloodType": "AB",
            "horoscope": "Scorpio",
            "height": "163cm",
            "nickname": "Raisha",
            "generation": "10",
            "jiko": "Kalau sakura itu kembang, Aku itu kembanggaanmu! Halo aku Raisha.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/SW_RaishaJKT48",
                "instagram": "https://www.instagram.com/jkt48.raisha.s/",
                "tiktok": "https://www.tiktok.com/@jkt48.raisha.s/",
                "threads": "https://www.threads.net/@jkt48.raisha.s",
                "showroom": "https://www.showroom-live.com/JKT48_Raisha",
                "idn_app": "https://www.idn.app/jkt48_raisha",
            },
        },
        {
            "id": 260,
            "name": "Alya Amanda",
            "href": "https://jkt48.com/member/detail/id/260?lang=id",
            "img": "https://jkt48.com/profile/alya_amanda.jpg?v=20231212",
            "birthdate": "26 Agustus 2006",
            "bloodType": "A",
            "horoscope": "Virgo",
            "height": "165cm",
            "nickname": "Alya",
            "generation": "11",
            "jiko": "Jika hatimu sedang menangis, aku akan datang sebagai pelangi. Halo, aku Alya!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/AA_AlyaJKT48",
                "instagram": "https://www.instagram.com/jkt48.alya_/",
                "tiktok": "https://www.tiktok.com/@alyajkt48/",
                "threads": "https://www.threads.net/@jkt48.alya_",
                "showroom": "https://www.showroom-live.com/JKT48_Alya",
                "idn_app": "https://www.idn.app/jkt48_alya",
            },
        },
        {
            "id": 262,
            "name": "Anindya Ramadhani",
            "href": "https://jkt48.com/member/detail/id/262?lang=id",
            "img": "https://jkt48.com/profile/anindya_ramadhani.jpg?v=20231212",
            "birthdate": "18 Oktober 2005",
            "bloodType": "O",
            "horoscope": "Libra",
            "height": "154cm",
            "nickname": "Anindya",
            "generation": "11",
            "jiko": "Si mungil hadir semanis mangga. Hai, aku Anindya!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/AR_AnindyaJKT48",
                "instagram": "https://www.instagram.com/jkt48.anindya_/",
                "tiktok": "https://www.tiktok.com/@anindyajkt48/",
                "threads": "https://www.threads.net/@jkt48.anindya_",
                "showroom": "https://www.showroom-live.com/JKT48_Anindya",
                "idn_app": "https://www.idn.app/jkt48_anindya",
            },
        },
        {
            "id": 263,
            "name": "Cathleen Nixie",
            "href": "https://jkt48.com/member/detail/id/263?lang=id",
            "img": "https://jkt48.com/profile/cathleen_nixie.jpg?v=20231212",
            "birthdate": "28 Mei 2009",
            "bloodType": "A",
            "horoscope": "Gemini",
            "height": "158cm",
            "nickname": "Cathy",
            "generation": "11",
            "jiko": "Si peri cantik jelita itulah aku. Hai, aku Cathy!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/N_CathyJKT48",
                "instagram": "https://www.instagram.com/jkt48.cathy/",
                "tiktok": "https://www.tiktok.com/@cathyjkt48/",
                "threads": "https://www.threads.net/@jkt48.cathy",
                "showroom": "https://www.showroom-live.com/JKT48_Cathy",
                "idn_app": "https://www.idn.app/jkt48_cathy",
            },
        },
        {
            "id": 264,
            "name": "Celline Thefani",
            "href": "https://jkt48.com/member/detail/id/264?lang=id",
            "img": "https://jkt48.com/profile/celline_thefani.jpg?v=20231212",
            "birthdate": "9 April 2007",
            "bloodType": "O",
            "horoscope": "Aries",
            "height": "163cm",
            "nickname": "Elin",
            "generation": "11",
            "jiko": "Semanis permen kapas dan seindah bunga lavender! Hollaa, perkenalkan nama aku Elin.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Elin_JKT48",
                "instagram": "https://www.instagram.com/jkt48.elin_/",
                "tiktok": "https://www.tiktok.com/@elinjkt48/",
                "threads": "https://www.threads.net/@jkt48.elin_",
                "showroom": "https://www.showroom-live.com/JKT48_Elin",
                "idn_app": "https://www.idn.app/jkt48_elin",
            },
        },
        {
            "id": 265,
            "name": "Chelsea Davina",
            "href": "https://jkt48.com/member/detail/id/265?lang=id",
            "img": "https://jkt48.com/profile/chelsea_davina.jpg?v=20231212",
            "birthdate": "23 Desember 2009",
            "bloodType": "B",
            "horoscope": "Capricorn",
            "height": "168cm",
            "nickname": "Chelsea",
            "generation": "11",
            "jiko": "As bright as the shooting stars in the starry night sky. Hello, I'm Chelsea!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/DC_ChelseaJKT48",
                "instagram": "https://www.instagram.com/jkt48.chelsea/",
                "tiktok": "https://www.tiktok.com/@_chelseajkt48/",
                "threads": "https://www.threads.net/@jkt48.chelsea",
                "showroom": "https://www.showroom-live.com/JKT48_Chelsea",
                "idn_app": "https://www.idn.app/jkt48_chelsea",
            },
        },
        {
            "id": 266,
            "name": "Cynthia Yaputera",
            "href": "https://jkt48.com/member/detail/id/266?lang=id",
            "img": "https://jkt48.com/profile/cynthia_yaputera.jpg?v=20231212",
            "birthdate": "22 November 2003",
            "bloodType": "O",
            "horoscope": "Sagitarius",
            "height": "158cm",
            "nickname": "Cynthia",
            "generation": "11",
            "jiko": "Semangatku terus menerus meluap, pop pop. Aku Cynthia!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Y_CynthiaJKT48",
                "instagram": "https://www.instagram.com/jkt48.cynthia/",
                "tiktok": "https://www.tiktok.com/@cynthiajkt48/",
                "threads": "https://www.threads.net/@jkt48.cynthia",
                "showroom": "https://www.showroom-live.com/JKT48_Cynthia",
                "idn_app": "https://www.idn.app/jkt48_cynthia",
            },
        },
        {
            "id": 267,
            "name": "Dena Natalia",
            "href": "https://jkt48.com/member/detail/id/267?lang=id",
            "img": "https://jkt48.com/profile/dena_natalia.jpg?v=20231212",
            "birthdate": "16 Desember 2005",
            "bloodType": "O",
            "horoscope": "Sagitarius",
            "height": "162cm",
            "nickname": "Danella",
            "generation": "11",
            "jiko": "Tok Tok, Siapa? Si penari yang akan menarikmu ke duniaku.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Danella_JKT48",
                "instagram": "https://www.instagram.com/jkt48.danella/",
                "tiktok": "https://www.tiktok.com/@danellajkt48/",
                "threads": "https://www.threads.net/@jkt48.danella",
                "showroom": "https://www.showroom-live.com/JKT48_Danella",
                "idn_app": "https://www.idn.app/jkt48_danella",
            },
        },
        {
            "id": 268,
            "name": "Desy Natalia",
            "href": "https://jkt48.com/member/detail/id/268?lang=id",
            "img": "https://jkt48.com/profile/desy_natalia.jpg?v=20231212",
            "birthdate": "16 Desember 2005",
            "bloodType": "O",
            "horoscope": "Sagitarius",
            "height": "165cm",
            "nickname": "Daisy",
            "generation": "11",
            "jiko": "Seperti bunga daisy, aku akan memancarkan kesegaran dan kebahagiaan.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Daisy_JKT48",
                "instagram": "https://www.instagram.com/jkt48.daisy/",
                "tiktok": "https://www.tiktok.com/@daisyjkt48/",
                "threads": "https://www.threads.net/@jkt48.daisy",
                "showroom": "https://www.showroom-live.com/JKT48_Daisy",
                "idn_app": "https://www.idn.app/jkt48_daisy",
            },
        },
        {
            "id": 269,
            "name": "Gendis Mayrannisa",
            "href": "https://jkt48.com/member/detail/id/269?lang=id",
            "img": "https://jkt48.com/profile/gendis_mayrannisa.jpg?v=20231212",
            "birthdate": "23 Juni 2010",
            "bloodType": "B",
            "horoscope": "Cancer",
            "height": "160cm",
            "nickname": "Gendis",
            "generation": "11",
            "jiko": "Bonjour, periang dan pencair suasana itulah aku, Gendis!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Gendis_JKT48",
                "instagram": "https://www.instagram.com/jkt48.gendis/",
                "tiktok": "https://www.tiktok.com/@gendisjkt48/",
                "threads": "https://www.threads.net/@jkt48.gendis",
                "showroom": "https://www.showroom-live.com/JKT48_Gendis",
                "idn_app": "https://www.idn.app/jkt48_gendis",
            },
        },
        {
            "id": 270,
            "name": "Grace Octaviani",
            "href": "https://jkt48.com/member/detail/id/270?lang=id",
            "img": "https://jkt48.com/profile/grace_octaviani.jpg?v=20231212",
            "birthdate": "18 Oktober 2007",
            "bloodType": "B",
            "horoscope": "Libra",
            "height": "165cm",
            "nickname": "Gracie",
            "generation": "11",
            "jiko": "Manis seperti gulali, imut seperti kelinci. Halo, aku Gracie!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Gracie_JKT48",
                "instagram": "https://www.instagram.com/jkt48.gracie/",
                "tiktok": "https://www.tiktok.com/@graciejkt48/",
                "threads": "https://www.threads.net/@jkt48.gracie",
                "showroom": "https://www.showroom-live.com/JKT48_Gracie",
                "idn_app": "https://www.idn.app/jkt48_gracie",
            },
        },
        {
            "id": 271,
            "name": "Greesella Adhalia",
            "href": "https://jkt48.com/member/detail/id/271?lang=id",
            "img": "https://jkt48.com/profile/greesella_adhalia.jpg?v=20231212",
            "birthdate": "10 Januari 2006",
            "bloodType": "O",
            "horoscope": "Capricorn",
            "height": "165cm",
            "nickname": "Greesel",
            "generation": "11",
            "jiko": "Pandangan mataku akan menyinari hatimu bagaikan kunang-kunang di malam hari.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Greesel_JKT48",
                "instagram": "https://www.instagram.com/jkt48.greesel/",
                "tiktok": "https://www.tiktok.com/@greeseljkt48/",
                "threads": "https://www.threads.net/@jkt48.greesel",
                "showroom": "https://www.showroom-live.com/JKT48_Greesel",
                "idn_app": "https://www.idn.app/jkt48_greesel",
            },
        },
        {
            "id": 273,
            "name": "Michelle Alexandra",
            "href": "https://jkt48.com/member/detail/id/273?lang=id",
            "img": "https://jkt48.com/profile/michelle_alexandra.jpg?v=20231212",
            "birthdate": "22 April 2009",
            "bloodType": "O",
            "horoscope": "Taurus",
            "height": "160cm",
            "nickname": "Michie",
            "generation": "11",
            "jiko": "Always your number one, till infinity and beyond. Hello everyone, it's Michie!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Michie_JKT48",
                "instagram": "https://www.instagram.com/jkt48.michie_/",
                "tiktok": "https://www.tiktok.com/@michiejkt48/",
                "threads": "https://www.threads.net/@jkt48.michie_",
                "showroom": "https://www.showroom-live.com/JKT48_Michie",
                "idn_app": "https://www.idn.app/jkt48_michie",
            },
        },
        {
            "id": 277,
            "name": "Abigail Rachel",
            "href": "https://jkt48.com/member/detail/id/277?lang=id",
            "img": "https://jkt48.com/profile/abigail_rachel.jpg",
            "birthdate": "6 Agustus 2008",
            "bloodType": "B",
            "horoscope": "Leo",
            "height": "161cm",
            "nickname": "Aralie",
            "generation": "12",
            "jiko": "Seperti bunga yang mekar, aku akan membuat kamu, kamu, dan kamu terbayang-bayang. Aku Ara-Aralie!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Aralie_JKT48",
                "instagram": "https://www.instagram.com/jkt48.aralie/",
                "tiktok": "https://www.tiktok.com/@jkt48.aralie/",
                "threads": "https://www.threads.net/@jkt48.aralie",
                "showroom": "https://www.showroom-live.com/JKT48_Aralie",
                "idn_app": "https://www.idn.app/aralie_jkt48",
            },
        },
        {
            "id": 278,
            "name": "Adeline Wijaya",
            "href": "https://jkt48.com/member/detail/id/278?lang=id",
            "img": "https://jkt48.com/profile/adeline_wijaya.jpg",
            "birthdate": "1 September 2007",
            "bloodType": "B",
            "horoscope": "Virgo",
            "height": "167cm",
            "nickname": "Delynn",
            "generation": "12",
            "jiko": "Nyemangatin dan ngangenin, siapa yang kamu pikirin? Delynn! Pyong pyong, aku Delynn.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Delynn_JKT48",
                "instagram": "https://www.instagram.com/jkt48.delynn/",
                "tiktok": "https://www.tiktok.com/@jkt48.delynn/",
                "threads": "https://www.threads.net/@jkt48.delynn",
                "showroom": "https://www.showroom-live.com/JKT48_Delynn",
                "idn_app": "https://www.idn.app/jkt48_delynn",
            },
        },
        {
            "id": 280,
            "name": "Aurhel Alana",
            "href": "https://jkt48.com/member/detail/id/280?lang=id",
            "img": "https://jkt48.com/profile/aurhel_alana.jpg?v=20231212",
            "birthdate": "14 September 2006",
            "bloodType": "-",
            "horoscope": "Virgo",
            "height": "163cm",
            "nickname": "Lana",
            "generation": "12",
            "jiko": "Dengan kekuatan bulan Aku akan menyihirmu dengan pesonaku! Hai aku Lana.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/AR_LanaJKT48",
                "instagram": "https://www.instagram.com/jkt48.lana.a/",
                "tiktok": "https://www.tiktok.com/@jkt48.lana/",
                "threads": "https://www.threads.net/@jkt48.lana.a",
                "showroom": "https://www.showroom-live.com/JKT48_Lana",
                "idn_app": "https://www.idn.app/jkt48_lana",
            },
        },
        {
            "id": 281,
            "name": "Catherina Vallencia",
            "href": "https://jkt48.com/member/detail/id/281?lang=id",
            "img": "https://jkt48.com/profile/catherina_vallencia.jpg",
            "birthdate": "21 Agustus 2007",
            "bloodType": "B",
            "horoscope": "Leo",
            "height": "163cm",
            "nickname": "Erine",
            "generation": "12",
            "jiko": "Hadir dengan seribu kejutan, Checkmate! Siap memenangkan hatimu. Halo semuanya, namaku Erine.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Cerine_JKT48",
                "instagram": "https://www.instagram.com/jkt48.erine/",
                "tiktok": "https://www.tiktok.com/@jkt48.erine_/",
                "threads": "https://www.threads.net/@jkt48.erine",
                "showroom": "https://www.showroom-live.com/JKT48_Erine",
                "idn_app": "https://www.idn.app/jkt48_erine",
            },
        },
        {
            "id": 282,
            "name": "Fritzy Rosmerian",
            "href": "https://jkt48.com/member/detail/id/282?lang=id",
            "img": "https://jkt48.com/profile/fritzy_rosmerian.jpg",
            "birthdate": "28 Juli 2008",
            "bloodType": "A",
            "horoscope": "Leo",
            "height": "157cm",
            "nickname": "Fritzy",
            "generation": "12",
            "jiko": "ABRACADABRA! Si pesulap yang siap membuat hatimu terpikat! Halo semuanya! It's me Fritzy!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/RFritzy_JKT48",
                "instagram": "https://www.instagram.com/jkt48.fritzy.r/",
                "tiktok": "https://www.tiktok.com/@jkt48.fritzy.r/",
                "threads": "https://www.threads.net/@jkt48.fritzy.r",
                "showroom": "https://www.showroom-live.com/JKT48_Fritzy",
                "idn_app": "https://www.idn.app/jkt48_fritzy",
            },
        },
        {
            "id": 283,
            "name": "Hillary Abigail",
            "href": "https://jkt48.com/member/detail/id/283?lang=id",
            "img": "https://jkt48.com/profile/hillary_abigail.jpg",
            "birthdate": "19 Oktober 2007",
            "bloodType": "O",
            "horoscope": "Libra",
            "height": "160cm",
            "nickname": "Lily",
            "generation": "12",
            "jiko": "Papipapipu aku akan mengejutkanmu dengan kehebatan ku. Halo aku Lily!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Lily_JKT48",
                "instagram": "https://www.instagram.com/jkt48.lily_/",
                "tiktok": "https://www.tiktok.com/@jkt48.lily/",
                "threads": "https://www.threads.net/@jkt48.lily_",
                "showroom": "https://www.showroom-live.com/JKT48_Lily",
                "idn_app": "https://www.idn.app/jkt48_lily",
            },
        },
        {
            "id": 284,
            "name": "Jazzlyn Trisha",
            "href": "https://jkt48.com/member/detail/id/284?lang=id",
            "img": "https://jkt48.com/profile/jazzlyn_trisha.jpg",
            "birthdate": "16 Februari 2011",
            "bloodType": "O",
            "horoscope": "Aquarius",
            "height": "164cm",
            "nickname": "Trisha",
            "generation": "12",
            "jiko": "Pelukis yang hadir di mimpi-mimpi indahmu. One… two… tri… sha! Halo semua, aku Trisha.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/JTrisha_JKT48",
                "instagram": "https://www.instagram.com/jkt48.trisha/",
                "tiktok": "https://www.tiktok.com/@jkt48.trisha/",
                "threads": "https://www.threads.net/@jkt48.trisha",
                "showroom": "https://www.showroom-live.com/JKT48_Trisha",
                "idn_app": "https://www.idn.app/jkt48_trisha",
            },
        },
        {
            "id": 286,
            "name": "Michelle Levia",
            "href": "https://jkt48.com/member/detail/id/286?lang=id",
            "img": "https://jkt48.com/profile/michelle_levia.jpg",
            "birthdate": "24 Januari 2009",
            "bloodType": "O",
            "horoscope": "Aquarius",
            "height": "168cm",
            "nickname": "Levi",
            "generation": "12",
            "jiko": "Are you ready? Jalani hari ini dengan menari bersamaku! Yuhu, aku Levi.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Levi_JKT48",
                "instagram": "https://www.instagram.com/jkt48.levi/",
                "tiktok": "https://www.tiktok.com/@jkt48.levi/",
                "threads": "https://www.threads.net/@jkt48.levi",
                "showroom": "https://www.showroom-live.com/JKT48_Levi",
                "idn_app": "https://www.idn.app/jkt48_levi",
            },
        },
        {
            "id": 287,
            "name": "Nayla Suji",
            "href": "https://jkt48.com/member/detail/id/287?lang=id",
            "img": "https://jkt48.com/profile/nayla_suji.jpg",
            "birthdate": "18 Juni 2007",
            "bloodType": "AB",
            "horoscope": "Gemini",
            "height": "161cm",
            "nickname": "Nayla",
            "generation": "12",
            "jiko": "Bakkyun! Tembakan cintaku akan melelehkan hatimu. Halo, aku Nayla!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/SNayla_JKT48",
                "instagram": "https://www.instagram.com/jkt48.nayla.s/",
                "tiktok": "https://www.tiktok.com/@jkt48.nayla/",
                "threads": "https://www.threads.net/@jkt48.nayla.s",
                "showroom": "https://www.showroom-live.com/JKT48_Nayla",
                "idn_app": "https://www.idn.app/jkt48_nayla",
            },
        },
        {
            "id": 288,
            "name": "Nina Tutachia",
            "href": "https://jkt48.com/member/detail/id/288?lang=id",
            "img": "https://jkt48.com/profile/nina_tutachia.jpg?v=20231212",
            "birthdate": "16 Oktober 2009",
            "bloodType": "O",
            "horoscope": "Libra",
            "height": "162cm",
            "nickname": "Nachia",
            "generation": "12",
            "jiko": "Si panda unyu yang selalu ceria! Hai aku Nachia.. bikin kamu bahagia!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Nachia_JKT48",
                "instagram": "https://www.instagram.com/jkt48.nachia.t/",
                "tiktok": "https://www.tiktok.com/@jkt48.nachia/",
                "threads": "https://www.threads.net/@jkt48.nachia.t",
                "showroom": "https://www.showroom-live.com/JKT48_Nachia",
                "idn_app": "https://www.idn.app/jkt48_nachia",
            },
        },
        {
            "id": 289,
            "name": "Oline Manuel",
            "href": "https://jkt48.com/member/detail/id/289?lang=id",
            "img": "https://jkt48.com/profile/oline_manuel.jpg",
            "birthdate": "3 November 2007",
            "bloodType": "B",
            "horoscope": "Scorpio",
            "height": "167cm",
            "nickname": "Oline",
            "generation": "12",
            "jiko": "Semangatku Full terus Gas! Gas! Gas! Oline!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/M_OlineJKT48",
                "instagram": "https://www.instagram.com/jkt48.oline/",
                "tiktok": "https://www.tiktok.com/@jkt48.oline/",
                "threads": "https://www.threads.net/@jkt48.oline",
                "showroom": "https://www.showroom-live.com/JKT48_Oline",
                "idn_app": "https://www.idn.app/jkt48_oline",
            },
        },
        {
            "id": 291,
            "name": "Ribka Budiman",
            "href": "https://jkt48.com/member/detail/id/291?lang=id",
            "img": "https://jkt48.com/profile/ribka_budiman.jpg",
            "birthdate": "13 Januari 2009",
            "bloodType": "O",
            "horoscope": "Capricorn",
            "height": "163cm",
            "nickname": "Ribka",
            "generation": "12",
            "jiko": "Mirror mirror on the wall, who's the sweetest in here? It's me, Ribka!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Ribka_JKT48",
                "instagram": "https://www.instagram.com/jkt48.ribka/",
                "tiktok": "https://www.tiktok.com/@jkt48.ribka/",
                "threads": "https://www.threads.net/@jkt48.ribka",
                "showroom": "https://www.showroom-live.com/JKT48_Ribka",
                "idn_app": "https://www.idn.app/jkt48_ribka",
            },
        },
        {
            "id": 292,
            "name": "Shabilqis Naila",
            "href": "https://jkt48.com/member/detail/id/292?lang=id",
            "img": "https://jkt48.com/profile/shabilqis_naila.jpg",
            "birthdate": "1 September 2008",
            "bloodType": "B",
            "horoscope": "Virgo",
            "height": "160cm",
            "nickname": "Nala",
            "generation": "12",
            "jiko": "ROAR! Si singa pemberani yang siap menyemangati harimu. Hai-hai aku Nala.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Nala_JKT48",
                "instagram": "https://www.instagram.com/jkt48.nala/",
                "tiktok": "https://www.tiktok.com/@jkt48.nala/",
                "threads": "https://www.threads.net/@jkt48.nala",
                "showroom": "https://www.showroom-live.com/JKT48_Nala",
                "idn_app": "https://www.idn.app/jkt48_nala",
            },
        },
        {
            "id": 293,
            "name": "Victoria Kimberly",
            "href": "https://jkt48.com/member/detail/id/293?lang=id",
            "img": "https://jkt48.com/profile/victoria_kimberly.jpg",
            "birthdate": "8 Maret 2010",
            "bloodType": "AB",
            "horoscope": "Pisces",
            "height": "158cm",
            "nickname": "Kimmy",
            "generation": "12",
            "jiko": "Baby hamster yang lincah, aku akan berlari-lari di pikiranmu! Halo-ha, katakan Kimmy!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Kimmy_JKT48",
                "instagram": "https://www.instagram.com/jkt48.kimmy/",
                "tiktok": "https://www.tiktok.com/@jkt48.kimmy/",
                "threads": "https://www.threads.net/@jkt48.kimmy",
                "showroom": "https://www.showroom-live.com/JKT48_Kimmy",
                "idn_app": "https://www.idn.app/jkt48_kimmy",
            },
        },
        {
            "id": 297,
            "name": "Astrella Virgiananda",
            "href": "https://jkt48.com/member/detail/id/297?lang=id",
            "img": "https://jkt48.com/profile/Astrella_Virgiananda.jpg",
            "birthdate": "6 Agustus 2010",
            "bloodType": "AB",
            "horoscope": "Leo",
            "height": "162cm",
            "nickname": "Virgi",
            "generation": "13",
            "jiko": "Suka berekspresi melalui kreasi. Tara! Aku Virgi!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/A_VirgiJKT48",
                "instagram": "https://www.instagram.com/virgi.jkt48/",
                "tiktok": "https://www.tiktok.com/@jkt48.virgi/",
                "threads": "https://www.threads.net/@virgi.jkt48",
                "showroom": "https://www.showroom-live.com/JKT48_Virgi",
                "idn_app": "https://www.idn.app/jkt48_virgi",
            },
        },
        {
            "id": 298,
            "name": "Aulia Riza",
            "href": "https://jkt48.com/member/detail/id/298?lang=id",
            "img": "https://jkt48.com/profile/Aulia_Riza.jpg",
            "birthdate": "14 Juli 2007",
            "bloodType": "O",
            "horoscope": "Cancer",
            "height": "166cm",
            "nickname": "Auwia",
            "generation": "13",
            "jiko": "Serigala tangguh di bawah sinar purnama. Panggil aku Auuu-wia!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Auwia_JKT48",
                "instagram": "https://www.instagram.com/auwia.jkt48/",
                "tiktok": "https://www.tiktok.com/@jkt48.auwia/",
                "threads": "https://www.threads.net/@auwia.jkt48",
                "showroom": "https://www.showroom-live.com/JKT48_Auwia",
                "idn_app": "https://www.idn.app/jkt48_auwia",
            },
        },
        {
            "id": 299,
            "name": "Bong Aprilli",
            "href": "https://jkt48.com/member/detail/id/299?lang=id",
            "img": "https://jkt48.com/profile/Bong_Aprilli.jpg",
            "birthdate": "1 April 2010",
            "bloodType": "A",
            "horoscope": "Aries",
            "height": "164cm",
            "nickname": "Rilly",
            "generation": "13",
            "jiko": "Bagaikan harmoni indah yang berirama di benakmu. Hai, aku Rilly!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Rilly_JKT48",
                "instagram": "https://www.instagram.com/rilly.jkt48_/",
                "tiktok": "https://www.tiktok.com/@jkt48.rilly/",
                "threads": "https://www.threads.net/@rilly.jkt48_",
                "showroom": "https://www.showroom-live.com/JKT48_Rilly",
                "idn_app": "https://www.idn.app/jkt48_rilly",
            },
        },
        {
            "id": 300,
            "name": "Hagia Sopia",
            "href": "https://jkt48.com/member/detail/id/300?lang=id",
            "img": "https://jkt48.com/profile/Hagia_Sopia.jpg",
            "birthdate": "1 Juli 2008",
            "bloodType": "O",
            "horoscope": "Cancer",
            "height": "166cm",
            "nickname": "Giaa",
            "generation": "13",
            "jiko": "Dengan semangat dan kerja kerasku. Aku akan membuat kalian bahagia. Halo panggil aku Gia!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Giaa_JKT48",
                "instagram": "https://www.instagram.com/giaa.jkt48/",
                "tiktok": "https://www.tiktok.com/@jkt48.giaa/",
                "threads": "https://www.threads.net/@giaa.jkt48",
                "showroom": "https://www.showroom-live.com/JKT48_Giaa",
                "idn_app": "https://www.idn.app/jkt48_giaa",
            },
        },
        {
            "id": 301,
            "name": "Humaira Ramadhani",
            "href": "https://jkt48.com/member/detail/id/301?lang=id",
            "img": "https://jkt48.com/profile/Humaira_Ramadhani.jpg",
            "birthdate": "13 Agustus 2011",
            "bloodType": "A",
            "horoscope": "Leo",
            "height": "156cm",
            "nickname": "Maira",
            "generation": "13",
            "jiko": "Penceria yang membuatmu tertawa dengan tingkahku. Halo semuanya, aku Maira!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Maira_JKT48",
                "instagram": "https://www.instagram.com/maira.jkt48/",
                "tiktok": "https://www.tiktok.com/@jkt48.maira/",
                "threads": "https://www.threads.net/@maira.jkt48",
                "showroom": "https://www.showroom-live.com/JKT48_Maira",
                "idn_app": "https://www.idn.app/jkt48_maira",
            },
        },
        {
            "id": 302,
            "name": "Jacqueline Immanuela",
            "href": "https://jkt48.com/member/detail/id/302?lang=id",
            "img": "https://jkt48.com/profile/Jacqueline_Immanuela.jpg",
            "birthdate": "9 Juli 2009",
            "bloodType": "B",
            "horoscope": "Cancer",
            "height": "160cm",
            "nickname": "Ekin",
            "generation": "13",
            "jiko": "Sesejuk dan sedingin mint. Perkenalkan, aku Ekin.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/Ekin_JKT48",
                "instagram": "https://www.instagram.com/ekin.jkt48/",
                "tiktok": "https://www.tiktok.com/@jkt48.ekin/",
                "threads": "https://www.threads.net/@ekin.jkt48",
                "showroom": "https://www.showroom-live.com/JKT48_Ekin",
                "idn_app": "https://www.idn.app/jkt48_ekin",
            },
        },
        {
            "id": 303,
            "name": "Jemima Evodie",
            "href": "https://jkt48.com/member/detail/id/303?lang=id",
            "img": "https://jkt48.com/profile/Jemima_Evodie.jpg",
            "birthdate": "9 November 2009",
            "bloodType": "O",
            "horoscope": "Scorpio",
            "height": "165cm",
            "nickname": "Jemima",
            "generation": "13",
            "jiko": "Ci...luk...ba! Merpati yang akan membawa kejutan di setiap penampilanku. Halo aku Jemima!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/JE_JemimaJKT48",
                "instagram": "https://www.instagram.com/jemima.jkt48/",
                "tiktok": "https://www.tiktok.com/@jkt48.jemima/",
                "threads": "https://www.threads.net/@jemima.jkt48",
                "showroom": "https://www.showroom-live.com/JKT48_Jemima",
                "idn_app": "https://www.idn.app/jkt48_jemima",
            },
        },
        {
            "id": 304,
            "name": "Mikaela Kusjanto",
            "href": "https://jkt48.com/member/detail/id/304?lang=id",
            "img": "https://jkt48.com/profile/Mikaela_Kusjanto.jpg",
            "birthdate": "15 Desember 2007",
            "bloodType": "O",
            "horoscope": "Sagitarius",
            "height": "166cm",
            "nickname": "Mikaela",
            "generation": "13",
            "jiko": "Camera... Roll... Action! Sutradara yang akan mewarnai kisah hidupmu dengan penuh warna. Hai Aku Mikaela!",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/M_MikaelaJKT48",
                "instagram": "https://www.instagram.com/mikaela.jkt48/",
                "tiktok": "https://www.tiktok.com/@jkt48.mikaela/",
                "threads": "https://www.threads.net/@mikaela.jkt48",
                "showroom": "https://www.showroom-live.com/JKT48_Mikaela",
                "idn_app": "https://www.idn.app/jkt48_mikaela",
            },
        },
        {
            "id": 305,
            "name": "Nur Intan",
            "href": "https://jkt48.com/member/detail/id/305?lang=id",
            "img": "https://jkt48.com/profile/Nur_Intan.jpg",
            "birthdate": "24 Februari 2006",
            "bloodType": "B",
            "horoscope": "Pisces",
            "height": "157cm",
            "nickname": "Intan",
            "generation": "13",
            "jiko": "Intan permata yang berkilau, temukan cahayaku di hatimu! Halo aku Intan.",
            "active": True,
            "socials": {
                "twitter": "https://twitter.com/N_IntanJKT48",
                "instagram": "https://www.instagram.com/intan.jkt48/",
                "tiktok": "https://www.tiktok.com/@jkt48.intan/",
                "threads": "https://www.threads.net/@intan.jkt48",
                "showroom": "https://www.showroom-live.com/JKT48_Intan",
                "idn_app": "https://www.idn.app/jkt48_intan",
            },
        },
    ]
