#!/usr/bin/env python3
"""
Database Seed Script for JKT48 Members and Setlists

This script contains both the seed data and the seeding logic.
Run manually - NOT exposed as an API endpoint for security.

Usage:
    source .venv/bin/activate
    python scripts/seed_database.py [--members] [--setlists] [--all]
"""

import argparse
import asyncio
import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src.database import database_instance

# JKT48 Active Members Data
JKT48_MEMBERS_DATA = [   {   'active': True,
        'birthdate': '16 Januari 1999',
        'bloodType': 'O',
        'generation': '3',
        'height': '162cm',
        'horoscope': 'Capricorn',
        'href': 'https://jkt48.com/member/detail/id/76?lang=id',
        'id': 76,
        'img': 'https://jkt48.com/profile/feni_fitriyanti.jpg?v=20230116',
        'jiko': 'Matahari yang indah, yang akan memberikan kehangatan di setiap harinya. Halo aku '
                'Feni.',
        'name': 'Feni Fitriyanti',
        'nickname': 'Feni',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_feni',
                       'instagram': 'https://www.instagram.com/jkt48feni/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Feni',
                       'threads': 'https://www.threads.net/@jkt48feni',
                       'tiktok': 'https://www.tiktok.com/@fenijkt48/',
                       'twitter': 'https://twitter.com/F_FeniJKT48'}},
    {   'active': True,
        'birthdate': '30 Juni 2001',
        'bloodType': 'O',
        'generation': '6',
        'height': '165cm',
        'horoscope': 'Cancer',
        'href': 'https://jkt48.com/member/detail/id/190?lang=id',
        'id': 190,
        'img': 'https://jkt48.com/profile/gita_sekar_andarini.jpg?v=20230116',
        'jiko': 'Diam bukan berarti tidak memperhatikanmu, aku Gita!',
        'name': 'Gita Sekar Andarini',
        'nickname': 'Gita',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_gita',
                       'instagram': 'https://www.instagram.com/jkt48gita/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Gita',
                       'threads': 'https://www.threads.net/@jkt48gita',
                       'tiktok': 'https://www.tiktok.com/@gitajkt48/',
                       'twitter': 'https://twitter.com/A_GitaJKT48'}},
    {   'active': True,
        'birthdate': '12 Juli 2004',
        'bloodType': 'B',
        'generation': '7',
        'height': '158cm',
        'horoscope': 'Cancer',
        'href': 'https://jkt48.com/member/detail/id/199?lang=id',
        'id': 199,
        'img': 'https://jkt48.com/profile/mutiara_azzahra.jpg?v=20230116',
        'jiko': 'Tok tok! Siapa? Si penari yang akan menarikmu ke duniaku.',
        'name': 'Mutiara Azzahra',
        'nickname': 'Muthe',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_muthe',
                       'instagram': 'https://www.instagram.com/jkt48.muthe_/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Muthe',
                       'threads': 'https://www.threads.net/@jkt48.muthe_',
                       'tiktok': 'https://www.tiktok.com/@muthejkt48/',
                       'twitter': 'https://twitter.com/A_MutheJKT48'}},
    {   'active': True,
        'birthdate': '5 Desember 2005',
        'bloodType': 'O',
        'generation': '7',
        'height': '163cm',
        'horoscope': 'Sagitarius',
        'href': 'https://jkt48.com/member/detail/id/204?lang=id',
        'id': 204,
        'img': 'https://jkt48.com/profile/angelina_christy.jpg?v=20230116',
        'jiko': 'Peduli dan berbaik hati, siapa dia? Chriiiis-ty!',
        'name': 'Angelina Christy',
        'nickname': 'Christy',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_christy',
                       'instagram': 'https://www.instagram.com/jkt48.christy/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Christy',
                       'threads': 'https://www.threads.net/@jkt48.christy',
                       'tiktok': 'https://www.tiktok.com/@christyjkt48/',
                       'twitter': 'https://twitter.com/A_ChristyJKT48'}},
    {   'active': True,
        'birthdate': '15 Juni 2000',
        'bloodType': 'A',
        'generation': '7',
        'height': '165cm',
        'horoscope': 'Gemini',
        'href': 'https://jkt48.com/member/detail/id/210?lang=id',
        'id': 210,
        'img': 'https://jkt48.com/profile/helisma_putri.jpg?v=20230116',
        'jiko': 'Dengan energi kegembiraanku, aku akan menghangatkan suasana. Halo halo, aku Ceu '
                'Eli!',
        'name': 'Helisma Putri',
        'nickname': 'Eli',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_eli',
                       'instagram': 'https://www.instagram.com/jkt48.eli/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Eli',
                       'threads': 'https://www.threads.net/@jkt48.eli',
                       'tiktok': 'https://www.tiktok.com/@elijkt48/',
                       'twitter': 'https://twitter.com/H_EliJKT48'}},
    {   'active': True,
        'birthdate': '26 Februari 2005',
        'bloodType': 'B',
        'generation': '7',
        'height': '154cm',
        'horoscope': 'Pisces',
        'href': 'https://jkt48.com/member/detail/id/213?lang=id',
        'id': 213,
        'img': 'https://jkt48.com/profile/febriola_sinambela.jpg?v=20230116',
        'jiko': 'Dengan keajaibanku, aku akan membuat kalian selalu tertawa. Halo, aku Olla, si '
                'mechanic girl!',
        'name': 'Febriola Sinambela',
        'nickname': 'Olla',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_olla',
                       'instagram': 'https://www.instagram.com/jkt48.olla/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Olla',
                       'threads': 'https://www.threads.net/@jkt48.olla',
                       'tiktok': 'https://www.tiktok.com/@ollajkt48/',
                       'twitter': 'https://twitter.com/F_OllaJKT48'}},
    {   'active': True,
        'birthdate': '13 Februari 2006',
        'bloodType': 'B',
        'generation': '7',
        'height': '154cm',
        'horoscope': 'Aquarius',
        'href': 'https://jkt48.com/member/detail/id/214?lang=id',
        'id': 214,
        'img': 'https://jkt48.com/profile/freya_jayawardana.jpg?v=20230116',
        'jiko': 'Gadis koleris yang suka berimajinasi, terangi harimu dengan senyum karamelku. '
                'Halo semua, aku Freya!',
        'name': 'Freya Jayawardana',
        'nickname': 'Freya',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_freya',
                       'instagram': 'https://www.instagram.com/jkt48.freya/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Freya',
                       'threads': 'https://www.threads.net/@jkt48.freya',
                       'tiktok': 'https://www.tiktok.com/@freyajkt48/',
                       'twitter': 'https://twitter.com/Freya_JKT48'}},
    {   'active': True,
        'birthdate': '23 September 2005',
        'bloodType': 'O',
        'generation': '7',
        'height': '163cm',
        'horoscope': 'Libra',
        'href': 'https://jkt48.com/member/detail/id/215?lang=id',
        'id': 215,
        'img': 'https://jkt48.com/profile/jessica_chandra.jpg?v=20230116',
        'jiko': 'Suka menari dan akan selalu berusaha menjadi sumber energimu. Hai, aku Jessi!',
        'name': 'Jessica Chandra',
        'nickname': 'Jessi',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_jessi',
                       'instagram': 'https://www.instagram.com/jkt48.jessi/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Jessi',
                       'threads': 'https://www.threads.net/@jkt48.jessi',
                       'tiktok': 'https://www.tiktok.com/@jessijkt48/',
                       'twitter': 'https://twitter.com/C_JessiJKT48'}},
    {   'active': True,
        'birthdate': '26 Juli 2002',
        'bloodType': 'O',
        'generation': '8',
        'height': '162cm',
        'horoscope': 'Leo',
        'href': 'https://jkt48.com/member/detail/id/221?lang=id',
        'id': 221,
        'img': 'https://jkt48.com/profile/cornelia_vanisa.jpg?v=20230116',
        'jiko': 'Si pelawak dengan jokes bapak-bapak yang akan menghiburmu. Halo, aku Oniel!',
        'name': 'Cornelia Vanisa',
        'nickname': 'Oniel',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_oniel',
                       'instagram': 'https://www.instagram.com/jkt48.oniel/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Oniel',
                       'threads': 'https://www.threads.net/@jkt48.oniel',
                       'tiktok': 'https://www.tiktok.com/@onieljkt48/',
                       'twitter': 'https://twitter.com/C_OnielJKT48'}},
    {   'active': True,
        'birthdate': '4 Februari 2002',
        'bloodType': 'O',
        'generation': '8',
        'height': '158cm',
        'horoscope': 'Aquarius',
        'href': 'https://jkt48.com/member/detail/id/223?lang=id',
        'id': 223,
        'img': 'https://jkt48.com/profile/fiony_alveria.jpg?v=20230116',
        'jiko': 'Seperti simfoni yang menenangkan hati. Halo aku Fiony!',
        'name': 'Fiony Alveria',
        'nickname': 'Fiony',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_fiony',
                       'instagram': 'https://www.instagram.com/jkt48.fiony/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Fiony',
                       'threads': 'https://www.threads.net/@jkt48.fiony',
                       'tiktok': 'https://www.tiktok.com/@fionyjkt48/',
                       'twitter': 'https://twitter.com/A_FionyJKT48'}},
    {   'active': True,
        'birthdate': '23 Oktober 2002',
        'bloodType': 'B',
        'generation': '8',
        'height': '157cm',
        'horoscope': 'Scorpio',
        'href': 'https://jkt48.com/member/detail/id/228?lang=id',
        'id': 228,
        'img': 'https://jkt48.com/profile/lulu_salsabila.jpg?v=20230116',
        'jiko': 'Terang seperti bulan, bersinar seperti bintang.. Aku Lulu!',
        'name': 'Lulu Salsabila',
        'nickname': 'Lulu',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_lulu',
                       'instagram': 'https://www.instagram.com/jkt48.lulu/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Lulu',
                       'threads': 'https://www.threads.net/@jkt48.lulu',
                       'tiktok': 'https://www.tiktok.com/@lulu_jkt48/',
                       'twitter': 'https://twitter.com/A_LuluJKT48'}},
    {   'active': True,
        'birthdate': '20 Maret 2001',
        'bloodType': 'A',
        'generation': '9',
        'height': '165cm',
        'horoscope': 'Pisces',
        'href': 'https://jkt48.com/member/detail/id/241?lang=id',
        'id': 241,
        'img': 'https://jkt48.com/profile/indah_cahya.jpg?v=20230116',
        'jiko': 'Tak banyak bicara, bercerita melalui tulisan. Hai aku Indah.',
        'name': 'Indah Cahya',
        'nickname': 'Indah',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_indah',
                       'instagram': 'https://www.instagram.com/jkt48indah_/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Indah',
                       'threads': 'https://www.threads.net/@jkt48indah_',
                       'tiktok': 'https://www.tiktok.com/@indahjkt48/',
                       'twitter': 'https://twitter.com/C_IndahJKT48'}},
    {   'active': True,
        'birthdate': '26 Juli 2006',
        'bloodType': 'A',
        'generation': '9',
        'height': '165cm',
        'horoscope': 'Leo',
        'href': 'https://jkt48.com/member/detail/id/242?lang=id',
        'id': 242,
        'img': 'https://jkt48.com/profile/kathrina_irene.jpg?v=20230116',
        'jiko': 'Never miss a chance to be a star. Halo, aku Kathrina!',
        'name': 'Kathrina Irene',
        'nickname': 'Kathrina',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_kathrina',
                       'instagram': 'https://www.instagram.com/jkt48.kathrina/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Kathrina',
                       'threads': 'https://www.threads.net/@jkt48.kathrina',
                       'tiktok': 'https://www.tiktok.com/@kathrinjkt48/',
                       'twitter': 'https://twitter.com/I_KathrinaJKT48'}},
    {   'active': True,
        'birthdate': '9 Januari 2006',
        'bloodType': 'O',
        'generation': '9',
        'height': '163cm',
        'horoscope': 'Capricorn',
        'href': 'https://jkt48.com/member/detail/id/243?lang=id',
        'id': 243,
        'img': 'https://jkt48.com/profile/marsha_lenathea.jpg?v=20230116',
        'jiko': 'Seperti piza yang dinanti-nantikan semua orang, selalu nantikan aku, ya! Halo, '
                'aku Marsha!',
        'name': 'Marsha Lenathea',
        'nickname': 'Marsha',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_marsha',
                       'instagram': 'https://www.instagram.com/jkt48.marsha/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Marsha',
                       'threads': 'https://www.threads.net/@jkt48.marsha',
                       'tiktok': 'https://www.tiktok.com/@marsha.jkt48/',
                       'twitter': 'https://twitter.com/L_MarshaJKT48'}},
    {   'active': True,
        'birthdate': '17 Desember 2004',
        'bloodType': 'O',
        'generation': '10',
        'height': '160cm',
        'horoscope': 'Sagitarius',
        'href': 'https://jkt48.com/member/detail/id/249?lang=id',
        'id': 249,
        'img': 'https://jkt48.com/profile/amanda_sukma.jpg?v=20230530',
        'jiko': 'Aku akan membuat hatimu berdebar kencang... Halo, aku Amanda!',
        'name': 'Amanda Sukma',
        'nickname': 'Amanda',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_amanda',
                       'instagram': 'https://www.instagram.com/jkt48.amanda.s/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Amanda',
                       'threads': 'https://www.threads.net/@jkt48.amanda.s',
                       'tiktok': 'https://www.tiktok.com/@jkt48.amanda.s/',
                       'twitter': 'https://twitter.com/PS_AmandaJKT48'}},
    {   'active': True,
        'birthdate': '29 Oktober 2002',
        'bloodType': 'O',
        'generation': '10',
        'height': '155cm',
        'horoscope': 'Scorpio',
        'href': 'https://jkt48.com/member/detail/id/250?lang=id',
        'id': 250,
        'img': 'https://jkt48.com/profile/aurellia.jpg?v=20230531',
        'jiko': 'Si social butterfly yang energik dan periang! Halo aku Aurellia.',
        'name': 'Aurellia',
        'nickname': 'Lia',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_aurellia',
                       'instagram': 'https://www.instagram.com/jkt48.aurellia_/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Aurellia',
                       'threads': 'https://www.threads.net/@jkt48.aurellia_',
                       'tiktok': 'https://www.tiktok.com/@jkt48.aurellia_/',
                       'twitter': 'https://twitter.com/AU_LiaJKT48'}},
    {   'active': True,
        'birthdate': '7 Agustus 2006',
        'bloodType': 'B',
        'generation': '10',
        'height': '160cm',
        'horoscope': 'Leo',
        'href': 'https://jkt48.com/member/detail/id/252?lang=id',
        'id': 252,
        'img': 'https://jkt48.com/profile/gabriela_abigail.jpg?v=20230531',
        'jiko': 'Ohayo! Konnichiwa! Oyasumi! Aku ingin ada di setiap harimu. Halo semuanya aku '
                'Ella.',
        'name': 'Gabriela Abigail',
        'nickname': 'Ella',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_ella',
                       'instagram': 'https://www.instagram.com/jkt48.ella.a/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Ella',
                       'threads': 'https://www.threads.net/@jkt48.ella.a',
                       'tiktok': 'https://www.tiktok.com/@jkt48.ella.a/',
                       'twitter': 'https://twitter.com/AM_EllaJKT48'}},
    {   'active': True,
        'birthdate': '26 April 2004',
        'bloodType': 'A',
        'generation': '10',
        'height': '160cm',
        'horoscope': 'Taurus',
        'href': 'https://jkt48.com/member/detail/id/253?lang=id',
        'id': 253,
        'img': 'https://jkt48.com/profile/indira_seruni.jpg?v=20230531',
        'jiko': 'Senyumanku menatap lurus ke arahmu, smiley eyes. Halo aku Indira.',
        'name': 'Indira Seruni',
        'nickname': 'Indira',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_indira',
                       'instagram': 'https://www.instagram.com/jkt48.indira.s/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Indira',
                       'threads': 'https://www.threads.net/@jkt48.indira.s',
                       'tiktok': 'https://www.tiktok.com/@jkt48.indira.s/',
                       'twitter': 'https://twitter.com/SP_IndiraJKT48'}},
    {   'active': True,
        'birthdate': '13 September 2001',
        'bloodType': 'O',
        'generation': '10',
        'height': '155cm',
        'horoscope': 'Virgo',
        'href': 'https://jkt48.com/member/detail/id/254?lang=id',
        'id': 254,
        'img': 'https://jkt48.com/profile/jesslyn_elly.jpg?v=20230531',
        'jiko': 'Seperti ombak laut yang tenang, tiba-tiba aku akan menyapumu dengan banyak cinta. '
                'Halo aku Lyn.',
        'name': 'Jesslyn Elly',
        'nickname': 'Lyn',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_lyn',
                       'instagram': 'https://www.instagram.com/jkt48.lyn.s/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Lyn',
                       'threads': 'https://www.threads.net/@jkt48.lyn.s',
                       'tiktok': 'https://www.tiktok.com/@jkt48.lyn.s/',
                       'twitter': 'https://twitter.com/SE_LynJKT48'}},
    {   'active': True,
        'birthdate': '11 November 2007',
        'bloodType': 'AB',
        'generation': '10',
        'height': '163cm',
        'horoscope': 'Scorpio',
        'href': 'https://jkt48.com/member/detail/id/255?lang=id',
        'id': 255,
        'img': 'https://jkt48.com/profile/raisha_syifa.jpg?v=20230530',
        'jiko': 'Kalau sakura itu kembang, Aku itu kembanggaanmu! Halo aku Raisha.',
        'name': 'Raisha Syifa',
        'nickname': 'Raisha',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_raisha',
                       'instagram': 'https://www.instagram.com/jkt48.raisha.s/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Raisha',
                       'threads': 'https://www.threads.net/@jkt48.raisha.s',
                       'tiktok': 'https://www.tiktok.com/@jkt48.raisha.s/',
                       'twitter': 'https://twitter.com/SW_RaishaJKT48'}},
    {   'active': True,
        'birthdate': '26 Agustus 2006',
        'bloodType': 'A',
        'generation': '11',
        'height': '165cm',
        'horoscope': 'Virgo',
        'href': 'https://jkt48.com/member/detail/id/260?lang=id',
        'id': 260,
        'img': 'https://jkt48.com/profile/alya_amanda.jpg?v=20231212',
        'jiko': 'Jika hatimu sedang menangis, aku akan datang sebagai pelangi. Halo, aku Alya!',
        'name': 'Alya Amanda',
        'nickname': 'Alya',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_alya',
                       'instagram': 'https://www.instagram.com/jkt48.alya_/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Alya',
                       'threads': 'https://www.threads.net/@jkt48.alya_',
                       'tiktok': 'https://www.tiktok.com/@alyajkt48/',
                       'twitter': 'https://twitter.com/AA_AlyaJKT48'}},
    {   'active': True,
        'birthdate': '18 Oktober 2005',
        'bloodType': 'O',
        'generation': '11',
        'height': '154cm',
        'horoscope': 'Libra',
        'href': 'https://jkt48.com/member/detail/id/262?lang=id',
        'id': 262,
        'img': 'https://jkt48.com/profile/anindya_ramadhani.jpg?v=20231212',
        'jiko': 'Si mungil hadir semanis mangga. Hai, aku Anindya!',
        'name': 'Anindya Ramadhani',
        'nickname': 'Anindya',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_anindya',
                       'instagram': 'https://www.instagram.com/jkt48.anindya_/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Anindya',
                       'threads': 'https://www.threads.net/@jkt48.anindya_',
                       'tiktok': 'https://www.tiktok.com/@anindyajkt48/',
                       'twitter': 'https://twitter.com/AR_AnindyaJKT48'}},
    {   'active': True,
        'birthdate': '28 Mei 2009',
        'bloodType': 'A',
        'generation': '11',
        'height': '158cm',
        'horoscope': 'Gemini',
        'href': 'https://jkt48.com/member/detail/id/263?lang=id',
        'id': 263,
        'img': 'https://jkt48.com/profile/cathleen_nixie.jpg?v=20231212',
        'jiko': 'Si peri cantik jelita itulah aku. Hai, aku Cathy!',
        'name': 'Cathleen Nixie',
        'nickname': 'Cathy',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_cathy',
                       'instagram': 'https://www.instagram.com/jkt48.cathy/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Cathy',
                       'threads': 'https://www.threads.net/@jkt48.cathy',
                       'tiktok': 'https://www.tiktok.com/@cathyjkt48/',
                       'twitter': 'https://twitter.com/N_CathyJKT48'}},
    {   'active': True,
        'birthdate': '9 April 2007',
        'bloodType': 'O',
        'generation': '11',
        'height': '163cm',
        'horoscope': 'Aries',
        'href': 'https://jkt48.com/member/detail/id/264?lang=id',
        'id': 264,
        'img': 'https://jkt48.com/profile/celline_thefani.jpg?v=20231212',
        'jiko': 'Semanis permen kapas dan seindah bunga lavender! Hollaa, perkenalkan nama aku '
                'Elin.',
        'name': 'Celline Thefani',
        'nickname': 'Elin',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_elin',
                       'instagram': 'https://www.instagram.com/jkt48.elin_/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Elin',
                       'threads': 'https://www.threads.net/@jkt48.elin_',
                       'tiktok': 'https://www.tiktok.com/@elinjkt48/',
                       'twitter': 'https://twitter.com/Elin_JKT48'}},
    {   'active': True,
        'birthdate': '23 Desember 2009',
        'bloodType': 'B',
        'generation': '11',
        'height': '168cm',
        'horoscope': 'Capricorn',
        'href': 'https://jkt48.com/member/detail/id/265?lang=id',
        'id': 265,
        'img': 'https://jkt48.com/profile/chelsea_davina.jpg?v=20231212',
        'jiko': "As bright as the shooting stars in the starry night sky. Hello, I'm Chelsea!",
        'name': 'Chelsea Davina',
        'nickname': 'Chelsea',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_chelsea',
                       'instagram': 'https://www.instagram.com/jkt48.chelsea/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Chelsea',
                       'threads': 'https://www.threads.net/@jkt48.chelsea',
                       'tiktok': 'https://www.tiktok.com/@_chelseajkt48/',
                       'twitter': 'https://twitter.com/DC_ChelseaJKT48'}},
    {   'active': True,
        'birthdate': '22 November 2003',
        'bloodType': 'O',
        'generation': '11',
        'height': '158cm',
        'horoscope': 'Sagitarius',
        'href': 'https://jkt48.com/member/detail/id/266?lang=id',
        'id': 266,
        'img': 'https://jkt48.com/profile/cynthia_yaputera.jpg?v=20231212',
        'jiko': 'Semangatku terus menerus meluap, pop pop. Aku Cynthia!',
        'name': 'Cynthia Yaputera',
        'nickname': 'Cynthia',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_cynthia',
                       'instagram': 'https://www.instagram.com/jkt48.cynthia/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Cynthia',
                       'threads': 'https://www.threads.net/@jkt48.cynthia',
                       'tiktok': 'https://www.tiktok.com/@cynthiajkt48/',
                       'twitter': 'https://twitter.com/Y_CynthiaJKT48'}},
    {   'active': True,
        'birthdate': '16 Desember 2005',
        'bloodType': 'O',
        'generation': '11',
        'height': '162cm',
        'horoscope': 'Sagitarius',
        'href': 'https://jkt48.com/member/detail/id/267?lang=id',
        'id': 267,
        'img': 'https://jkt48.com/profile/dena_natalia.jpg?v=20231212',
        'jiko': 'Tok Tok, Siapa? Si penari yang akan menarikmu ke duniaku.',
        'name': 'Dena Natalia',
        'nickname': 'Danella',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_danella',
                       'instagram': 'https://www.instagram.com/jkt48.danella/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Danella',
                       'threads': 'https://www.threads.net/@jkt48.danella',
                       'tiktok': 'https://www.tiktok.com/@danellajkt48/',
                       'twitter': 'https://twitter.com/Danella_JKT48'}},
    {   'active': True,
        'birthdate': '16 Desember 2005',
        'bloodType': 'O',
        'generation': '11',
        'height': '165cm',
        'horoscope': 'Sagitarius',
        'href': 'https://jkt48.com/member/detail/id/268?lang=id',
        'id': 268,
        'img': 'https://jkt48.com/profile/desy_natalia.jpg?v=20231212',
        'jiko': 'Seperti bunga daisy, aku akan memancarkan kesegaran dan kebahagiaan.',
        'name': 'Desy Natalia',
        'nickname': 'Daisy',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_daisy',
                       'instagram': 'https://www.instagram.com/jkt48.daisy/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Daisy',
                       'threads': 'https://www.threads.net/@jkt48.daisy',
                       'tiktok': 'https://www.tiktok.com/@daisyjkt48/',
                       'twitter': 'https://twitter.com/Daisy_JKT48'}},
    {   'active': True,
        'birthdate': '23 Juni 2010',
        'bloodType': 'B',
        'generation': '11',
        'height': '160cm',
        'horoscope': 'Cancer',
        'href': 'https://jkt48.com/member/detail/id/269?lang=id',
        'id': 269,
        'img': 'https://jkt48.com/profile/gendis_mayrannisa.jpg?v=20231212',
        'jiko': 'Bonjour, periang dan pencair suasana itulah aku, Gendis!',
        'name': 'Gendis Mayrannisa',
        'nickname': 'Gendis',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_gendis',
                       'instagram': 'https://www.instagram.com/jkt48.gendis/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Gendis',
                       'threads': 'https://www.threads.net/@jkt48.gendis',
                       'tiktok': 'https://www.tiktok.com/@gendisjkt48/',
                       'twitter': 'https://twitter.com/Gendis_JKT48'}},
    {   'active': True,
        'birthdate': '18 Oktober 2007',
        'bloodType': 'B',
        'generation': '11',
        'height': '165cm',
        'horoscope': 'Libra',
        'href': 'https://jkt48.com/member/detail/id/270?lang=id',
        'id': 270,
        'img': 'https://jkt48.com/profile/grace_octaviani.jpg?v=20231212',
        'jiko': 'Manis seperti gulali, imut seperti kelinci. Halo, aku Gracie!',
        'name': 'Grace Octaviani',
        'nickname': 'Gracie',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_gracie',
                       'instagram': 'https://www.instagram.com/jkt48.gracie/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Gracie',
                       'threads': 'https://www.threads.net/@jkt48.gracie',
                       'tiktok': 'https://www.tiktok.com/@graciejkt48/',
                       'twitter': 'https://twitter.com/Gracie_JKT48'}},
    {   'active': True,
        'birthdate': '10 Januari 2006',
        'bloodType': 'O',
        'generation': '11',
        'height': '165cm',
        'horoscope': 'Capricorn',
        'href': 'https://jkt48.com/member/detail/id/271?lang=id',
        'id': 271,
        'img': 'https://jkt48.com/profile/greesella_adhalia.jpg?v=20231212',
        'jiko': 'Pandangan mataku akan menyinari hatimu bagaikan kunang-kunang di malam hari.',
        'name': 'Greesella Adhalia',
        'nickname': 'Greesel',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_greesel',
                       'instagram': 'https://www.instagram.com/jkt48.greesel/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Greesel',
                       'threads': 'https://www.threads.net/@jkt48.greesel',
                       'tiktok': 'https://www.tiktok.com/@greeseljkt48/',
                       'twitter': 'https://twitter.com/Greesel_JKT48'}},
    {   'active': True,
        'birthdate': '22 April 2009',
        'bloodType': 'O',
        'generation': '11',
        'height': '160cm',
        'horoscope': 'Taurus',
        'href': 'https://jkt48.com/member/detail/id/273?lang=id',
        'id': 273,
        'img': 'https://jkt48.com/profile/michelle_alexandra.jpg?v=20231212',
        'jiko': "Always your number one, till infinity and beyond. Hello everyone, it's Michie!",
        'name': 'Michelle Alexandra',
        'nickname': 'Michie',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_michie',
                       'instagram': 'https://www.instagram.com/jkt48.michie_/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Michie',
                       'threads': 'https://www.threads.net/@jkt48.michie_',
                       'tiktok': 'https://www.tiktok.com/@michiejkt48/',
                       'twitter': 'https://twitter.com/Michie_JKT48'}},
    {   'active': True,
        'birthdate': '6 Agustus 2008',
        'bloodType': 'B',
        'generation': '12',
        'height': '161cm',
        'horoscope': 'Leo',
        'href': 'https://jkt48.com/member/detail/id/277?lang=id',
        'id': 277,
        'img': 'https://jkt48.com/profile/abigail_rachel.jpg',
        'jiko': 'Seperti bunga yang mekar, aku akan membuat kamu, kamu, dan kamu terbayang-bayang. '
                'Aku Ara-Aralie!',
        'name': 'Abigail Rachel',
        'nickname': 'Aralie',
        'socials': {   'idn_app': 'https://www.idn.app/aralie_jkt48',
                       'instagram': 'https://www.instagram.com/jkt48.aralie/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Aralie',
                       'threads': 'https://www.threads.net/@jkt48.aralie',
                       'tiktok': 'https://www.tiktok.com/@jkt48.aralie/',
                       'twitter': 'https://twitter.com/Aralie_JKT48'}},
    {   'active': True,
        'birthdate': '1 September 2007',
        'bloodType': 'B',
        'generation': '12',
        'height': '167cm',
        'horoscope': 'Virgo',
        'href': 'https://jkt48.com/member/detail/id/278?lang=id',
        'id': 278,
        'img': 'https://jkt48.com/profile/adeline_wijaya.jpg',
        'jiko': 'Nyemangatin dan ngangenin, siapa yang kamu pikirin? Delynn! Pyong pyong, aku '
                'Delynn.',
        'name': 'Adeline Wijaya',
        'nickname': 'Delynn',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_delynn',
                       'instagram': 'https://www.instagram.com/jkt48.delynn/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Delynn',
                       'threads': 'https://www.threads.net/@jkt48.delynn',
                       'tiktok': 'https://www.tiktok.com/@jkt48.delynn/',
                       'twitter': 'https://twitter.com/Delynn_JKT48'}},
    {   'active': True,
        'birthdate': '14 September 2006',
        'bloodType': '-',
        'generation': '12',
        'height': '163cm',
        'horoscope': 'Virgo',
        'href': 'https://jkt48.com/member/detail/id/280?lang=id',
        'id': 280,
        'img': 'https://jkt48.com/profile/aurhel_alana.jpg?v=20231212',
        'jiko': 'Dengan kekuatan bulan Aku akan menyihirmu dengan pesonaku! Hai aku Lana.',
        'name': 'Aurhel Alana',
        'nickname': 'Lana',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_lana',
                       'instagram': 'https://www.instagram.com/jkt48.lana.a/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Lana',
                       'threads': 'https://www.threads.net/@jkt48.lana.a',
                       'tiktok': 'https://www.tiktok.com/@jkt48.lana/',
                       'twitter': 'https://twitter.com/AR_LanaJKT48'}},
    {   'active': True,
        'birthdate': '21 Agustus 2007',
        'bloodType': 'B',
        'generation': '12',
        'height': '163cm',
        'horoscope': 'Leo',
        'href': 'https://jkt48.com/member/detail/id/281?lang=id',
        'id': 281,
        'img': 'https://jkt48.com/profile/catherina_vallencia.jpg',
        'jiko': 'Hadir dengan seribu kejutan, Checkmate! Siap memenangkan hatimu. Halo semuanya, '
                'namaku Erine.',
        'name': 'Catherina Vallencia',
        'nickname': 'Erine',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_erine',
                       'instagram': 'https://www.instagram.com/jkt48.erine/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Erine',
                       'threads': 'https://www.threads.net/@jkt48.erine',
                       'tiktok': 'https://www.tiktok.com/@jkt48.erine_/',
                       'twitter': 'https://twitter.com/Cerine_JKT48'}},
    {   'active': True,
        'birthdate': '28 Juli 2008',
        'bloodType': 'A',
        'generation': '12',
        'height': '157cm',
        'horoscope': 'Leo',
        'href': 'https://jkt48.com/member/detail/id/282?lang=id',
        'id': 282,
        'img': 'https://jkt48.com/profile/fritzy_rosmerian.jpg',
        'jiko': "ABRACADABRA! Si pesulap yang siap membuat hatimu terpikat! Halo semuanya! It's me "
                'Fritzy!',
        'name': 'Fritzy Rosmerian',
        'nickname': 'Fritzy',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_fritzy',
                       'instagram': 'https://www.instagram.com/jkt48.fritzy.r/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Fritzy',
                       'threads': 'https://www.threads.net/@jkt48.fritzy.r',
                       'tiktok': 'https://www.tiktok.com/@jkt48.fritzy.r/',
                       'twitter': 'https://twitter.com/RFritzy_JKT48'}},
    {   'active': True,
        'birthdate': '19 Oktober 2007',
        'bloodType': 'O',
        'generation': '12',
        'height': '160cm',
        'horoscope': 'Libra',
        'href': 'https://jkt48.com/member/detail/id/283?lang=id',
        'id': 283,
        'img': 'https://jkt48.com/profile/hillary_abigail.jpg',
        'jiko': 'Papipapipu aku akan mengejutkanmu dengan kehebatan ku. Halo aku Lily!',
        'name': 'Hillary Abigail',
        'nickname': 'Lily',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_lily',
                       'instagram': 'https://www.instagram.com/jkt48.lily_/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Lily',
                       'threads': 'https://www.threads.net/@jkt48.lily_',
                       'tiktok': 'https://www.tiktok.com/@jkt48.lily/',
                       'twitter': 'https://twitter.com/Lily_JKT48'}},
    {   'active': True,
        'birthdate': '16 Februari 2011',
        'bloodType': 'O',
        'generation': '12',
        'height': '164cm',
        'horoscope': 'Aquarius',
        'href': 'https://jkt48.com/member/detail/id/284?lang=id',
        'id': 284,
        'img': 'https://jkt48.com/profile/jazzlyn_trisha.jpg',
        'jiko': 'Pelukis yang hadir di mimpi-mimpi indahmu. One… two… tri… sha! Halo semua, aku '
                'Trisha.',
        'name': 'Jazzlyn Trisha',
        'nickname': 'Trisha',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_trisha',
                       'instagram': 'https://www.instagram.com/jkt48.trisha/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Trisha',
                       'threads': 'https://www.threads.net/@jkt48.trisha',
                       'tiktok': 'https://www.tiktok.com/@jkt48.trisha/',
                       'twitter': 'https://twitter.com/JTrisha_JKT48'}},
    {   'active': True,
        'birthdate': '24 Januari 2009',
        'bloodType': 'O',
        'generation': '12',
        'height': '168cm',
        'horoscope': 'Aquarius',
        'href': 'https://jkt48.com/member/detail/id/286?lang=id',
        'id': 286,
        'img': 'https://jkt48.com/profile/michelle_levia.jpg',
        'jiko': 'Are you ready? Jalani hari ini dengan menari bersamaku! Yuhu, aku Levi.',
        'name': 'Michelle Levia',
        'nickname': 'Levi',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_levi',
                       'instagram': 'https://www.instagram.com/jkt48.levi/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Levi',
                       'threads': 'https://www.threads.net/@jkt48.levi',
                       'tiktok': 'https://www.tiktok.com/@jkt48.levi/',
                       'twitter': 'https://twitter.com/Levi_JKT48'}},
    {   'active': True,
        'birthdate': '18 Juni 2007',
        'bloodType': 'AB',
        'generation': '12',
        'height': '161cm',
        'horoscope': 'Gemini',
        'href': 'https://jkt48.com/member/detail/id/287?lang=id',
        'id': 287,
        'img': 'https://jkt48.com/profile/nayla_suji.jpg',
        'jiko': 'Bakkyun! Tembakan cintaku akan melelehkan hatimu. Halo, aku Nayla!',
        'name': 'Nayla Suji',
        'nickname': 'Nayla',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_nayla',
                       'instagram': 'https://www.instagram.com/jkt48.nayla.s/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Nayla',
                       'threads': 'https://www.threads.net/@jkt48.nayla.s',
                       'tiktok': 'https://www.tiktok.com/@jkt48.nayla/',
                       'twitter': 'https://twitter.com/SNayla_JKT48'}},
    {   'active': True,
        'birthdate': '16 Oktober 2009',
        'bloodType': 'O',
        'generation': '12',
        'height': '162cm',
        'horoscope': 'Libra',
        'href': 'https://jkt48.com/member/detail/id/288?lang=id',
        'id': 288,
        'img': 'https://jkt48.com/profile/nina_tutachia.jpg?v=20231212',
        'jiko': 'Si panda unyu yang selalu ceria! Hai aku Nachia.. bikin kamu bahagia!',
        'name': 'Nina Tutachia',
        'nickname': 'Nachia',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_nachia',
                       'instagram': 'https://www.instagram.com/jkt48.nachia.t/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Nachia',
                       'threads': 'https://www.threads.net/@jkt48.nachia.t',
                       'tiktok': 'https://www.tiktok.com/@jkt48.nachia/',
                       'twitter': 'https://twitter.com/Nachia_JKT48'}},
    {   'active': True,
        'birthdate': '3 November 2007',
        'bloodType': 'B',
        'generation': '12',
        'height': '167cm',
        'horoscope': 'Scorpio',
        'href': 'https://jkt48.com/member/detail/id/289?lang=id',
        'id': 289,
        'img': 'https://jkt48.com/profile/oline_manuel.jpg',
        'jiko': 'Semangatku Full terus Gas! Gas! Gas! Oline!',
        'name': 'Oline Manuel',
        'nickname': 'Oline',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_oline',
                       'instagram': 'https://www.instagram.com/jkt48.oline/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Oline',
                       'threads': 'https://www.threads.net/@jkt48.oline',
                       'tiktok': 'https://www.tiktok.com/@jkt48.oline/',
                       'twitter': 'https://twitter.com/M_OlineJKT48'}},
    {   'active': True,
        'birthdate': '13 Januari 2009',
        'bloodType': 'O',
        'generation': '12',
        'height': '163cm',
        'horoscope': 'Capricorn',
        'href': 'https://jkt48.com/member/detail/id/291?lang=id',
        'id': 291,
        'img': 'https://jkt48.com/profile/ribka_budiman.jpg',
        'jiko': "Mirror mirror on the wall, who's the sweetest in here? It's me, Ribka!",
        'name': 'Ribka Budiman',
        'nickname': 'Ribka',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_ribka',
                       'instagram': 'https://www.instagram.com/jkt48.ribka/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Ribka',
                       'threads': 'https://www.threads.net/@jkt48.ribka',
                       'tiktok': 'https://www.tiktok.com/@jkt48.ribka/',
                       'twitter': 'https://twitter.com/Ribka_JKT48'}},
    {   'active': True,
        'birthdate': '1 September 2008',
        'bloodType': 'B',
        'generation': '12',
        'height': '160cm',
        'horoscope': 'Virgo',
        'href': 'https://jkt48.com/member/detail/id/292?lang=id',
        'id': 292,
        'img': 'https://jkt48.com/profile/shabilqis_naila.jpg',
        'jiko': 'ROAR! Si singa pemberani yang siap menyemangati harimu. Hai-hai aku Nala.',
        'name': 'Shabilqis Naila',
        'nickname': 'Nala',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_nala',
                       'instagram': 'https://www.instagram.com/jkt48.nala/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Nala',
                       'threads': 'https://www.threads.net/@jkt48.nala',
                       'tiktok': 'https://www.tiktok.com/@jkt48.nala/',
                       'twitter': 'https://twitter.com/Nala_JKT48'}},
    {   'active': True,
        'birthdate': '8 Maret 2010',
        'bloodType': 'AB',
        'generation': '12',
        'height': '158cm',
        'horoscope': 'Pisces',
        'href': 'https://jkt48.com/member/detail/id/293?lang=id',
        'id': 293,
        'img': 'https://jkt48.com/profile/victoria_kimberly.jpg',
        'jiko': 'Baby hamster yang lincah, aku akan berlari-lari di pikiranmu! Halo-ha, katakan '
                'Kimmy!',
        'name': 'Victoria Kimberly',
        'nickname': 'Kimmy',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_kimmy',
                       'instagram': 'https://www.instagram.com/jkt48.kimmy/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Kimmy',
                       'threads': 'https://www.threads.net/@jkt48.kimmy',
                       'tiktok': 'https://www.tiktok.com/@jkt48.kimmy/',
                       'twitter': 'https://twitter.com/Kimmy_JKT48'}},
    {   'active': True,
        'birthdate': '6 Agustus 2010',
        'bloodType': 'AB',
        'generation': '13',
        'height': '162cm',
        'horoscope': 'Leo',
        'href': 'https://jkt48.com/member/detail/id/297?lang=id',
        'id': 297,
        'img': 'https://jkt48.com/profile/Astrella_Virgiananda.jpg',
        'jiko': 'Suka berekspresi melalui kreasi. Tara! Aku Virgi!',
        'name': 'Astrella Virgiananda',
        'nickname': 'Virgi',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_virgi',
                       'instagram': 'https://www.instagram.com/virgi.jkt48/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Virgi',
                       'threads': 'https://www.threads.net/@virgi.jkt48',
                       'tiktok': 'https://www.tiktok.com/@jkt48.virgi/',
                       'twitter': 'https://twitter.com/A_VirgiJKT48'}},
    {   'active': True,
        'birthdate': '14 Juli 2007',
        'bloodType': 'O',
        'generation': '13',
        'height': '166cm',
        'horoscope': 'Cancer',
        'href': 'https://jkt48.com/member/detail/id/298?lang=id',
        'id': 298,
        'img': 'https://jkt48.com/profile/Aulia_Riza.jpg',
        'jiko': 'Serigala tangguh di bawah sinar purnama. Panggil aku Auuu-wia!',
        'name': 'Aulia Riza',
        'nickname': 'Auwia',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_auwia',
                       'instagram': 'https://www.instagram.com/auwia.jkt48/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Auwia',
                       'threads': 'https://www.threads.net/@auwia.jkt48',
                       'tiktok': 'https://www.tiktok.com/@jkt48.auwia/',
                       'twitter': 'https://twitter.com/Auwia_JKT48'}},
    {   'active': True,
        'birthdate': '1 April 2010',
        'bloodType': 'A',
        'generation': '13',
        'height': '164cm',
        'horoscope': 'Aries',
        'href': 'https://jkt48.com/member/detail/id/299?lang=id',
        'id': 299,
        'img': 'https://jkt48.com/profile/Bong_Aprilli.jpg',
        'jiko': 'Bagaikan harmoni indah yang berirama di benakmu. Hai, aku Rilly!',
        'name': 'Bong Aprilli',
        'nickname': 'Rilly',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_rilly',
                       'instagram': 'https://www.instagram.com/rilly.jkt48_/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Rilly',
                       'threads': 'https://www.threads.net/@rilly.jkt48_',
                       'tiktok': 'https://www.tiktok.com/@jkt48.rilly/',
                       'twitter': 'https://twitter.com/Rilly_JKT48'}},
    {   'active': True,
        'birthdate': '1 Juli 2008',
        'bloodType': 'O',
        'generation': '13',
        'height': '166cm',
        'horoscope': 'Cancer',
        'href': 'https://jkt48.com/member/detail/id/300?lang=id',
        'id': 300,
        'img': 'https://jkt48.com/profile/Hagia_Sopia.jpg',
        'jiko': 'Dengan semangat dan kerja kerasku. Aku akan membuat kalian bahagia. Halo panggil '
                'aku Gia!',
        'name': 'Hagia Sopia',
        'nickname': 'Giaa',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_giaa',
                       'instagram': 'https://www.instagram.com/giaa.jkt48/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Giaa',
                       'threads': 'https://www.threads.net/@giaa.jkt48',
                       'tiktok': 'https://www.tiktok.com/@jkt48.giaa/',
                       'twitter': 'https://twitter.com/Giaa_JKT48'}},
    {   'active': True,
        'birthdate': '13 Agustus 2011',
        'bloodType': 'A',
        'generation': '13',
        'height': '156cm',
        'horoscope': 'Leo',
        'href': 'https://jkt48.com/member/detail/id/301?lang=id',
        'id': 301,
        'img': 'https://jkt48.com/profile/Humaira_Ramadhani.jpg',
        'jiko': 'Penceria yang membuatmu tertawa dengan tingkahku. Halo semuanya, aku Maira!',
        'name': 'Humaira Ramadhani',
        'nickname': 'Maira',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_maira',
                       'instagram': 'https://www.instagram.com/maira.jkt48/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Maira',
                       'threads': 'https://www.threads.net/@maira.jkt48',
                       'tiktok': 'https://www.tiktok.com/@jkt48.maira/',
                       'twitter': 'https://twitter.com/Maira_JKT48'}},
    {   'active': True,
        'birthdate': '9 Juli 2009',
        'bloodType': 'B',
        'generation': '13',
        'height': '160cm',
        'horoscope': 'Cancer',
        'href': 'https://jkt48.com/member/detail/id/302?lang=id',
        'id': 302,
        'img': 'https://jkt48.com/profile/Jacqueline_Immanuela.jpg',
        'jiko': 'Sesejuk dan sedingin mint. Perkenalkan, aku Ekin.',
        'name': 'Jacqueline Immanuela',
        'nickname': 'Ekin',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_ekin',
                       'instagram': 'https://www.instagram.com/ekin.jkt48/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Ekin',
                       'threads': 'https://www.threads.net/@ekin.jkt48',
                       'tiktok': 'https://www.tiktok.com/@jkt48.ekin/',
                       'twitter': 'https://twitter.com/Ekin_JKT48'}},
    {   'active': True,
        'birthdate': '9 November 2009',
        'bloodType': 'O',
        'generation': '13',
        'height': '165cm',
        'horoscope': 'Scorpio',
        'href': 'https://jkt48.com/member/detail/id/303?lang=id',
        'id': 303,
        'img': 'https://jkt48.com/profile/Jemima_Evodie.jpg',
        'jiko': 'Ci...luk...ba! Merpati yang akan membawa kejutan di setiap penampilanku. Halo aku '
                'Jemima!',
        'name': 'Jemima Evodie',
        'nickname': 'Jemima',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_jemima',
                       'instagram': 'https://www.instagram.com/jemima.jkt48/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Jemima',
                       'threads': 'https://www.threads.net/@jemima.jkt48',
                       'tiktok': 'https://www.tiktok.com/@jkt48.jemima/',
                       'twitter': 'https://twitter.com/JE_JemimaJKT48'}},
    {   'active': True,
        'birthdate': '15 Desember 2007',
        'bloodType': 'O',
        'generation': '13',
        'height': '166cm',
        'horoscope': 'Sagitarius',
        'href': 'https://jkt48.com/member/detail/id/304?lang=id',
        'id': 304,
        'img': 'https://jkt48.com/profile/Mikaela_Kusjanto.jpg',
        'jiko': 'Camera... Roll... Action! Sutradara yang akan mewarnai kisah hidupmu dengan penuh '
                'warna. Hai Aku Mikaela!',
        'name': 'Mikaela Kusjanto',
        'nickname': 'Mikaela',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_mikaela',
                       'instagram': 'https://www.instagram.com/mikaela.jkt48/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Mikaela',
                       'threads': 'https://www.threads.net/@mikaela.jkt48',
                       'tiktok': 'https://www.tiktok.com/@jkt48.mikaela/',
                       'twitter': 'https://twitter.com/M_MikaelaJKT48'}},
    {   'active': True,
        'birthdate': '24 Februari 2006',
        'bloodType': 'B',
        'generation': '13',
        'height': '157cm',
        'horoscope': 'Pisces',
        'href': 'https://jkt48.com/member/detail/id/305?lang=id',
        'id': 305,
        'img': 'https://jkt48.com/profile/Nur_Intan.jpg',
        'jiko': 'Intan permata yang berkilau, temukan cahayaku di hatimu! Halo aku Intan.',
        'name': 'Nur Intan',
        'nickname': 'Intan',
        'socials': {   'idn_app': 'https://www.idn.app/jkt48_intan',
                       'instagram': 'https://www.instagram.com/intan.jkt48/',
                       'showroom': 'https://www.showroom-live.com/JKT48_Intan',
                       'threads': 'https://www.threads.net/@intan.jkt48',
                       'tiktok': 'https://www.tiktok.com/@jkt48.intan/',
                       'twitter': 'https://twitter.com/N_IntanJKT48'}}]
# JKT48 Theater Setlists Data
JKT48_SETLISTS_DATA = [   {   'active': True,
        'description': 'Setlist original JKT48 yang menampilkan tema pengorbanan, cinta, dan emosi '
                       'mendalam dengan nuansa dewasa.',
        'imageUrl': 'https://res.cloudinary.com/doig4w6cm/image/fetch/f_webp,q_80,ar_0.75,w_640,c_fill/https://res.cloudinary.com/haymzm4wp/image/upload/v1760105446/wwiaxahqs3ti0lhqdszz.jpg',
        'setlistId': '07a4875a-be97-4238-972f-594e941d17db',
        'songs': [],
        'title': 'Pertaruhan Cinta',
        'titleJapanese': 'Aisuru Hito no Tame ni',
        'type': 'setlist'},
    {   'active': True,
        'description': 'Setlist penuh energi dan ceria yang sering menjadi favorit karena '
                       'interaksi member yang kuat.',
        'imageUrl': 'https://res.cloudinary.com/doig4w6cm/image/fetch/f_webp,q_80,ar_0.75,w_640,c_fill/https://res.cloudinary.com/haymzm4wp/image/upload/v1717174034/xspjxcs9wwm9jxwhiy5q.jpg',
        'setlistId': 'b754ab55-178d-4907-b471-154194d6cb52',
        'songs': [],
        'title': 'Pajama Drive',
        'titleJapanese': 'Pajama Drive',
        'type': 'setlist'},
    {   'active': False,
        'description': 'Setlist ikonik dengan tema larangan cinta yang kuat dan koreografi tajam.',
        'imageUrl': 'https://cdn.idntimes.com/content-images/post/20251115/50a27780-93e7-4e40-8474-60f6e0cca6da-251115200115.jpg',
        'setlistId': '64ec97af-b21f-4393-8139-374e179fec9d',
        'songs': [],
        'title': 'Aturan Anti Cinta',
        'titleJapanese': 'Renai Kinshi Jourei',
        'type': 'setlist'},
    {   'active': False,
        'description': 'Setlist dengan nuansa semangat dan harapan.',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48',
        'setlistId': 'ef28a998-ff88-438c-83e6-3e92d3257dfc',
        'songs': [],
        'title': 'Matahari Milikku',
        'titleJapanese': 'Boku no Taiyou',
        'type': 'setlist'},
    {   'active': False,
        'description': 'Setlist emosional dengan tema pengorbanan.',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48',
        'setlistId': '46de442e-bf77-4c1d-8fd5-0d68adc7f0aa',
        'songs': [],
        'title': 'Demi Seseorang',
        'titleJapanese': 'Dareka no Tame ni',
        'type': 'setlist'},
    {   'active': False,
        'description': 'Setlist penuh energi dengan tema masa remaja.',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48',
        'setlistId': '0899649d-aeea-498c-8f5d-6215f2a88b90',
        'songs': [],
        'title': 'Gadis Gadis Remaja',
        'titleJapanese': 'Seishun Girls',
        'type': 'setlist'},
    {   'active': True,
        'description': 'Setlist bernuansa kedewasaan dan refleksi.',
        'imageUrl': 'https://res.cloudinary.com/doig4w6cm/image/fetch/f_webp,q_80,ar_0.75,w_640,c_fill/https://res.cloudinary.com/haymzm4wp/image/upload/v1743898507/nvw4gqjtdhje2ftxt9i1.jpg',
        'setlistId': '82a499a5-d45e-451c-bc30-a09bd8d9bd80',
        'songs': [],
        'title': 'Sambil Menggandeng Erat Tanganku',
        'titleJapanese': 'Te wo Tsunaginagara',
        'type': 'setlist'},
    {   'active': False,
        'description': 'Setlist penghormatan terhadap panggung theater.',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48',
        'setlistId': '8c4f9e74-26f2-4196-b789-a5ac1f2f3a2f',
        'songs': [],
        'title': 'Dewi Theater',
        'titleJapanese': 'Theater no Megami',
        'type': 'setlist'},
    {   'active': False,
        'description': 'Setlist bertema perpisahan.',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48',
        'setlistId': 'e2920b79-7374-439b-939b-42891fd54516',
        'songs': [],
        'title': 'Bel Terakhir Berbunyi',
        'titleJapanese': 'Saishuu Bell ga Naru',
        'type': 'setlist'},
    {   'active': False,
        'description': 'Setlist dengan dinamika emosi naik turun.',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48',
        'setlistId': '86a80fa2-bd6d-4d65-a57a-8852a289ea5a',
        'songs': [],
        'title': 'Saka Agari',
        'titleJapanese': 'Saka Agari',
        'type': 'setlist'},
    {   'active': False,
        'description': 'Setlist romantis dan ringan.',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48',
        'setlistId': 'a7b5f371-53e1-4710-9bce-05e97681b8d8',
        'songs': [],
        'title': 'Sekarang Sedang Jatuh Cinta',
        'titleJapanese': 'Ima Koi wo Shiteru',
        'type': 'setlist'},
    {   'active': False,
        'description': 'Setlist perjuangan awal seorang idol.',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48',
        'setlistId': 'd2f74396-ca3d-4760-a803-14b8c19c53d6',
        'songs': [],
        'title': 'Fajar Sang Idola',
        'titleJapanese': 'Idol no Yoake',
        'type': 'setlist'},
    {   'active': False,
        'description': 'Setlist bertema pertumbuhan generasi muda.',
        'imageUrl': 'https://res.cloudinary.com/doig4w6cm/image/fetch/f_webp,q_80,ar_0.75,w_640,c_fill/https://res.cloudinary.com/haymzm4wp/image/upload/v1698750703/uploads/yvryrdy47ppla0nidn3m.webp',
        'setlistId': '00fba8ac-d90e-4468-9620-4898b430580e',
        'songs': [],
        'title': 'Tunas di Balik Seragam',
        'titleJapanese': 'Seifuku no Me',
        'type': 'setlist'},
    {   'active': True,
        'description': 'Setlist ceria dan penuh warna.',
        'imageUrl': 'https://res.cloudinary.com/doig4w6cm/image/fetch/f_webp,q_80,ar_0.75,w_640,c_fill/https://res.cloudinary.com/haymzm4wp/image/upload/v1702404446/nixg3rixpjpom3xa0ivf.jpg',
        'setlistId': '8b55b1e8-c4ba-42fc-8832-2caab8b0ff69',
        'songs': [],
        'title': 'Cara Meminum Ramune',
        'titleJapanese': 'Ramune no Nomikata',
        'type': 'setlist'},
    {   'active': False,
        'description': 'Setlist klasik pembuka perjalanan JKT48.',
        'imageUrl': 'https://res.cloudinary.com/doig4w6cm/image/fetch/f_webp,q_80,ar_0.75,w_640,c_fill/https://res.cloudinary.com/haymzm4wp/image/upload/v1697224788/uploads/w2zvghwk8tocey8e8xhv.jpg',
        'setlistId': '388ba1cb-c70d-4e16-b5cc-4933077ae729',
        'songs': [],
        'title': 'Ingin Bertemu',
        'titleJapanese': 'Aitakatta',
        'type': 'setlist'},
    {   'active': False,
        'description': 'Setlist spesial dengan konsep cerah dan playful.',
        'imageUrl': 'https://res.cloudinary.com/doig4w6cm/image/fetch/f_webp,q_80,ar_0.75,w_640,c_fill/https://res.cloudinary.com/haymzm4wp/image/upload/v1763233779/tanfbrrf8oexxmmfoouh.jpg',
        'setlistId': 'ef9ba259-460f-4260-8d54-4aa362b659de',
        'songs': [],
        'title': 'KIRA KIRA GIRLS',
        'titleJapanese': 'Kira Kira Girls',
        'type': 'setlist'},
    {   'active': False,
        'description': 'Di JKT48 School, para Trainee akan menjadi murid yang siap belajar, '
                       'berkembang, dan mengeksplorasi potensi mereka. Setiap kelas bukan hanya '
                       'tempat menimba ilmu, tetapi juga panggung untuk menunjukkan sisi lain yang '
                       'belum pernah terlihat, dengan kejutan dari bintang tamu spesial! Yuk, '
                       'ikuti JKT48 School dan kenali para trainee lebih dekat! Saksikan semangat '
                       'mereka di setiap kelas untuk tumbuh bersama dan semakin bersinar. Pastinya '
                       'kamu akan menemukan sisi baru yang membuatmu semakin jatuh hati!',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48+EVENT',
        'setlistId': 'de513614-cdd0-4b09-85c0-357d67e2f2d1',
        'title': 'JKT48 SCHOOL',
        'type': 'event'},
    {   'active': False,
        'description': 'Seluruh MC terkemuka JKT48 akan bersatu untuk menghadirkan tawa dan canda '
                       'tiada dua. Apakah kalian penasaran bagaimana mereka beradu skill menjadi '
                       'seorang host, atau bahkan kemampuan mereka dalam membuka mic? Saksikan '
                       'hanya di Host Sweet Host!',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48+EVENT',
        'setlistId': '397fecbc-6313-42a7-9911-d419b411138b',
        'title': 'HOST SWEET HOST',
        'type': 'event'},
    {   'active': False,
        'description': 'THE BATTLE: VOCAL QUEENS akan mempertemukan kita dengan para member JKT48 '
                       'bersuara emas. Tidak hanya mendengarkan mereka bernyanyi, namun kita juga '
                       'akan melihat dan menguji beragam teknik vokal yang mereka miliki. Ayo '
                       'bersama kita temukan, siapa Vocal Queen JKT48 sesungguhnya.',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48+EVENT',
        'setlistId': 'ad0f02a0-567c-4dae-a10d-10cf2044e2b8',
        'title': 'THE BATTLE: VOCAL QUEENS',
        'type': 'event'},
    {   'active': False,
        'description': 'THE BATTLE: DANCING QUEEN akan menghadirkan para member JKT48 dengan skill '
                       'dance terbaik! Dalam acara ini, mereka akan saling berhadapan dalam sebuah '
                       'battle untuk menunjukkan siapa yang pantas menyandang gelar "Dancing '
                       'Queen". Tak hanya itu, mereka juga akan menghadapi tantangan untuk menguji '
                       'kreativitas, kecepatan, dan kekompakan. Siapakah member yang akan '
                       'membuktikan diri sebagai dancer terbaik?',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48+EVENT',
        'setlistId': '01d3fc7c-ae3f-4641-b6e3-7a2429781f33',
        'title': 'THE BATTLE: DANCING QUEENS',
        'type': 'event'},
    {   'active': False,
        'description': 'Menampilkan sisi lain dari kehidupan sekelompok manusia yang bekerja dalam '
                       'sebuah kantor "Ahensi Kreatif" di salah satu kota besar di Indonesia. '
                       'Seringkali kita dihadapkan pada berbagai pilihan yang menyulitkan dalam '
                       'dinamika pekerjaan. Bahkan beberapa dari kalian mungkin akan memilih takut '
                       '"deadline" daripada takut hantu. Dikemas dalam dialog yang "satire"- siap '
                       'menampar para budak korporat (baca; kita) yang berada dalam frekuensi yang '
                       'sama. Pepatah mengatakan "Rejeki sudah ada Signature", namun apakah benar '
                       'demikian? Simak kisahnya yang diracik semanis teh es buatan Marlina '
                       'Sihantam Meja! Kind reminder: Sampai bertemu di First Alignment, undangan '
                       'sudah kami kirimkan Cc email masing-masing!',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48+EVENT',
        'setlistId': '85d1807a-6143-4306-be45-3798d7cc321b',
        'title': 'CATUR ASTA',
        'type': 'event'},
    {   'active': False,
        'description': 'Family48 is back! Dalam acara ini, kita akan bersama-sama menyaksikan '
                       'member menebak jawaban terbanyak dari setiap pertanyaan yang telah melalui '
                       'sebuah survei khusus. Kecepatan berpikir dan kreativitas tentu menjadi '
                       'modal yang sangat penting untuk menemukan setiap jawaban. Saksikan '
                       'keseruannya, hanya di JKT48 Theater!',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48+EVENT',
        'setlistId': '81d1463b-99ef-4704-82f8-bd1705b8644d',
        'title': 'FAMILY48',
        'type': 'event'},
    {   'active': False,
        'description': 'QUIT GAME adalah sebuah acara spesial Ramadan yang mengusung tema game '
                       'show. Di acara ini, para member akan dihadapkan pada berbagai tantangan '
                       'permainan yang tidak hanya menguji kreativitas, tetapi juga mengasah kerja '
                       'sama tim dan fokus. Setiap tantangan dirancang untuk mengetes seberapa '
                       'solid dan kompak para member dalam menghadapi rintangan yang diberikan. '
                       'Apakah mereka bisa melewati setiap tantangan dengan sukses? Atau justru '
                       'akan menyerah di tengah jalan?',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48+EVENT',
        'setlistId': '4aedcfc1-9753-4c50-a619-68fa6c2564f1',
        'title': 'QUIT GAME',
        'type': 'event'},
    {   'active': False,
        'description': 'Panggilan untuk setiap member berprestasi di JKT48 untuk mengikuti Seleksi '
                       'Penelusuran Minat dan Kemampuan 2025. Seleksi ini juga berlaku bagi kalian '
                       'yang memiliki nilai rapor di atas rata-rata, untuk ikut menyaksikan '
                       'bagaimana member JKT48 adu kecerdasan untuk mendapatkan predikat "Einstein '
                       'di Masa Depan".',
        'imageUrl': 'https://placehold.co/640x960?text=JKT48+EVENT',
        'setlistId': '51183b54-b1c9-4c24-b3a7-6ecd16b626bc',
        'title': 'SELEKSI PMDK',
        'type': 'event'}]


async def seed_members(db) -> int:
    """Seed the database with JKT48 member data"""
    collection = db["members"]
    
    # Clear existing data
    await collection.delete_many({})
    
    # Insert new data
    result = await collection.insert_many(JKT48_MEMBERS_DATA)
    return len(result.inserted_ids)


async def seed_setlists(db) -> int:
    """Seed the database with JKT48 setlist data"""
    collection = db["setlists"]
    
    # Clear existing data
    await collection.delete_many({})
    
    # Insert new data
    result = await collection.insert_many(JKT48_SETLISTS_DATA)
    return len(result.inserted_ids)


async def main():
    parser = argparse.ArgumentParser(
        description="Seed the database with JKT48 data"
    )
    parser.add_argument(
        "--members", action="store_true", help="Seed only members data"
    )
    parser.add_argument(
        "--setlists", action="store_true", help="Seed only setlists data"
    )
    parser.add_argument(
        "--all", action="store_true", help="Seed all data (default)"
    )
    
    args = parser.parse_args()
    
    # Default to --all if no specific option is provided
    seed_all = args.all or (not args.members and not args.setlists)
    
    print("=" * 50)
    print("JKT48 Database Seed Script")
    print("=" * 50)
    print("\n⚠️  WARNING: This will DELETE and REPLACE existing data!")
    print("Press Ctrl+C to cancel...\n")
    
    # Wait 3 seconds to give user a chance to cancel
    await asyncio.sleep(3)
    
    print("Initializing database connection...")
    
    max_retries = 30
    retry_interval = 2
    
    for i in range(max_retries):
        try:
            await database_instance.connect()
            await database_instance.database.command("ping")
            print("✓ Successfully connected to MongoDB!")
            break
        except Exception as e:
            print(f"Waiting for database... (Attempt {i+1}/{max_retries}) Error: {e}")
            if i < max_retries - 1:
                await asyncio.sleep(retry_interval)
            else:
                print("✗ Could not connect to database after multiple attempts.")
                sys.exit(1)
    
    try:
        db = database_instance.database
        
        if seed_all or args.members:
            print("\nSeeding members data...")
            members_count = await seed_members(db)
            print(f"✓ Seeded {members_count} members successfully!")
        
        if seed_all or args.setlists:
            print("\nSeeding setlists data...")
            setlists_count = await seed_setlists(db)
            print(f"✓ Seeded {setlists_count} setlists successfully!")
        
        print("\n" + "=" * 50)
        print("Database seeding completed successfully!")
        print("=" * 50)
        
    except Exception as e:
        print(f"\n✗ Error during seeding: {e}")
        sys.exit(1)
    finally:
        print("\nClosing database connection...")
        await database_instance.close()


if __name__ == "__main__":
    asyncio.run(main())
