class Info:
    SETLIST_FOUND = "Setlist found successfully."
    SETLISTS_RETRIEVED = "Setlists retrieved successfully."
    SETLIST_DATA_SEEDED = "Setlist data seeded successfully."


class ErrorCode:
    SETLIST_NOT_FOUND = "Setlist not found."
    SETLIST_FETCH_ERROR = "Failed to fetch setlist data."


class DomainErrorCode:
    SETLIST_NOT_FOUND = "Setlist not found."
    SETLIST_FETCH_FAILED = "Failed to fetch setlist data."


# JKT48 Theater Setlists Data
class Jkt48Setlists:
    data = [
        {
            "setlistId": "07a4875a-be97-4238-972f-594e941d17db",
            "imageUrl": "https://res.cloudinary.com/doig4w6cm/image/fetch/f_webp,q_80,ar_0.75,w_640,c_fill/https://res.cloudinary.com/haymzm4wp/image/upload/v1760105446/wwiaxahqs3ti0lhqdszz.jpg",
            "title": "Pertaruhan Cinta",
            "titleJapanese": "Aisuru Hito no Tame ni",
            "description": "Setlist original JKT48 yang menampilkan tema pengorbanan, cinta, dan emosi mendalam dengan nuansa dewasa.",
            "type": "setlist",
            "active": True,
            "songs": [],
        },
        {
            "setlistId": "b754ab55-178d-4907-b471-154194d6cb52",
            "imageUrl": "https://res.cloudinary.com/doig4w6cm/image/fetch/f_webp,q_80,ar_0.75,w_640,c_fill/https://res.cloudinary.com/haymzm4wp/image/upload/v1717174034/xspjxcs9wwm9jxwhiy5q.jpg",
            "title": "Pajama Drive",
            "titleJapanese": "Pajama Drive",
            "description": "Setlist penuh energi dan ceria yang sering menjadi favorit karena interaksi member yang kuat.",
            "type": "setlist",
            "active": True,
            "songs": [],
        },
        {
            "setlistId": "64ec97af-b21f-4393-8139-374e179fec9d",
            "imageUrl": "https://cdn.idntimes.com/content-images/post/20251115/50a27780-93e7-4e40-8474-60f6e0cca6da-251115200115.jpg",
            "title": "Aturan Anti Cinta",
            "titleJapanese": "Renai Kinshi Jourei",
            "description": "Setlist ikonik dengan tema larangan cinta yang kuat dan koreografi tajam.",
            "type": "setlist",
            "active": False,
            "songs": [],
        },
        {
            "setlistId": "ef28a998-ff88-438c-83e6-3e92d3257dfc",
            "imageUrl": "https://placehold.co/640x960?text=JKT48",
            "title": "Matahari Milikku",
            "titleJapanese": "Boku no Taiyou",
            "description": "Setlist dengan nuansa semangat dan harapan.",
            "type": "setlist",
            "active": False,
            "songs": [],
        },
        {
            "setlistId": "46de442e-bf77-4c1d-8fd5-0d68adc7f0aa",
            "imageUrl": "https://placehold.co/640x960?text=JKT48",
            "title": "Demi Seseorang",
            "titleJapanese": "Dareka no Tame ni",
            "description": "Setlist emosional dengan tema pengorbanan.",
            "type": "setlist",
            "active": False,
            "songs": [],
        },
        {
            "setlistId": "0899649d-aeea-498c-8f5d-6215f2a88b90",
            "imageUrl": "https://placehold.co/640x960?text=JKT48",
            "title": "Gadis Gadis Remaja",
            "titleJapanese": "Seishun Girls",
            "description": "Setlist penuh energi dengan tema masa remaja.",
            "type": "setlist",
            "active": False,
            "songs": [],
        },
        {
            "setlistId": "82a499a5-d45e-451c-bc30-a09bd8d9bd80",
            "imageUrl": "https://res.cloudinary.com/doig4w6cm/image/fetch/f_webp,q_80,ar_0.75,w_640,c_fill/https://res.cloudinary.com/haymzm4wp/image/upload/v1743898507/nvw4gqjtdhje2ftxt9i1.jpg",
            "title": "Sambil Menggandeng Erat Tanganku",
            "titleJapanese": "Te wo Tsunaginagara",
            "description": "Setlist bernuansa kedewasaan dan refleksi.",
            "type": "setlist",
            "active": True,
            "songs": [],
        },
        {
            "setlistId": "8c4f9e74-26f2-4196-b789-a5ac1f2f3a2f",
            "imageUrl": "https://placehold.co/640x960?text=JKT48",
            "title": "Dewi Theater",
            "titleJapanese": "Theater no Megami",
            "description": "Setlist penghormatan terhadap panggung theater.",
            "type": "setlist",
            "active": False,
            "songs": [],
        },
        {
            "setlistId": "e2920b79-7374-439b-939b-42891fd54516",
            "imageUrl": "https://placehold.co/640x960?text=JKT48",
            "title": "Bel Terakhir Berbunyi",
            "titleJapanese": "Saishuu Bell ga Naru",
            "description": "Setlist bertema perpisahan.",
            "type": "setlist",
            "active": False,
            "songs": [],
        },
        {
            "setlistId": "86a80fa2-bd6d-4d65-a57a-8852a289ea5a",
            "imageUrl": "https://placehold.co/640x960?text=JKT48",
            "title": "Saka Agari",
            "titleJapanese": "Saka Agari",
            "description": "Setlist dengan dinamika emosi naik turun.",
            "type": "setlist",
            "active": False,
            "songs": [],
        },
        {
            "setlistId": "a7b5f371-53e1-4710-9bce-05e97681b8d8",
            "imageUrl": "https://placehold.co/640x960?text=JKT48",
            "title": "Sekarang Sedang Jatuh Cinta",
            "titleJapanese": "Ima Koi wo Shiteru",
            "description": "Setlist romantis dan ringan.",
            "type": "setlist",
            "active": False,
            "songs": [],
        },
        {
            "setlistId": "d2f74396-ca3d-4760-a803-14b8c19c53d6",
            "imageUrl": "https://placehold.co/640x960?text=JKT48",
            "title": "Fajar Sang Idola",
            "titleJapanese": "Idol no Yoake",
            "description": "Setlist perjuangan awal seorang idol.",
            "type": "setlist",
            "active": False,
            "songs": [],
        },
        {
            "setlistId": "00fba8ac-d90e-4468-9620-4898b430580e",
            "imageUrl": "https://res.cloudinary.com/doig4w6cm/image/fetch/f_webp,q_80,ar_0.75,w_640,c_fill/https://res.cloudinary.com/haymzm4wp/image/upload/v1698750703/uploads/yvryrdy47ppla0nidn3m.webp",
            "title": "Tunas di Balik Seragam",
            "titleJapanese": "Seifuku no Me",
            "description": "Setlist bertema pertumbuhan generasi muda.",
            "type": "setlist",
            "active": False,
            "songs": [],
        },
        {
            "setlistId": "8b55b1e8-c4ba-42fc-8832-2caab8b0ff69",
            "imageUrl": "https://res.cloudinary.com/doig4w6cm/image/fetch/f_webp,q_80,ar_0.75,w_640,c_fill/https://res.cloudinary.com/haymzm4wp/image/upload/v1702404446/nixg3rixpjpom3xa0ivf.jpg",
            "title": "Cara Meminum Ramune",
            "titleJapanese": "Ramune no Nomikata",
            "description": "Setlist ceria dan penuh warna.",
            "type": "setlist",
            "active": True,
            "songs": [],
        },
        {
            "setlistId": "388ba1cb-c70d-4e16-b5cc-4933077ae729",
            "imageUrl": "https://res.cloudinary.com/doig4w6cm/image/fetch/f_webp,q_80,ar_0.75,w_640,c_fill/https://res.cloudinary.com/haymzm4wp/image/upload/v1697224788/uploads/w2zvghwk8tocey8e8xhv.jpg",
            "title": "Ingin Bertemu",
            "titleJapanese": "Aitakatta",
            "description": "Setlist klasik pembuka perjalanan JKT48.",
            "type": "setlist",
            "active": False,
            "songs": [],
        },
        {
            "setlistId": "ef9ba259-460f-4260-8d54-4aa362b659de",
            "imageUrl": "https://res.cloudinary.com/doig4w6cm/image/fetch/f_webp,q_80,ar_0.75,w_640,c_fill/https://res.cloudinary.com/haymzm4wp/image/upload/v1763233779/tanfbrrf8oexxmmfoouh.jpg",
            "title": "KIRA KIRA GIRLS",
            "titleJapanese": "Kira Kira Girls",
            "description": "Setlist spesial dengan konsep cerah dan playful.",
            "type": "setlist",
            "active": False,
            "songs": [],
        },
        # Events
        {
            "setlistId": "de513614-cdd0-4b09-85c0-357d67e2f2d1",
            "imageUrl": "https://placehold.co/640x960?text=JKT48+EVENT",
            "title": "JKT48 SCHOOL",
            "description": "Di JKT48 School, para Trainee akan menjadi murid yang siap belajar, berkembang, dan mengeksplorasi potensi mereka. Setiap kelas bukan hanya tempat menimba ilmu, tetapi juga panggung untuk menunjukkan sisi lain yang belum pernah terlihat, dengan kejutan dari bintang tamu spesial! Yuk, ikuti JKT48 School dan kenali para trainee lebih dekat! Saksikan semangat mereka di setiap kelas untuk tumbuh bersama dan semakin bersinar. Pastinya kamu akan menemukan sisi baru yang membuatmu semakin jatuh hati!",
            "type": "event",
            "active": False,
        },
        {
            "setlistId": "397fecbc-6313-42a7-9911-d419b411138b",
            "imageUrl": "https://placehold.co/640x960?text=JKT48+EVENT",
            "title": "HOST SWEET HOST",
            "description": "Seluruh MC terkemuka JKT48 akan bersatu untuk menghadirkan tawa dan canda tiada dua. Apakah kalian penasaran bagaimana mereka beradu skill menjadi seorang host, atau bahkan kemampuan mereka dalam membuka mic? Saksikan hanya di Host Sweet Host!",
            "type": "event",
            "active": False,
        },
        {
            "setlistId": "ad0f02a0-567c-4dae-a10d-10cf2044e2b8",
            "imageUrl": "https://placehold.co/640x960?text=JKT48+EVENT",
            "title": "THE BATTLE: VOCAL QUEENS",
            "description": "THE BATTLE: VOCAL QUEENS akan mempertemukan kita dengan para member JKT48 bersuara emas. Tidak hanya mendengarkan mereka bernyanyi, namun kita juga akan melihat dan menguji beragam teknik vokal yang mereka miliki. Ayo bersama kita temukan, siapa Vocal Queen JKT48 sesungguhnya.",
            "type": "event",
            "active": False,
        },
        {
            "setlistId": "01d3fc7c-ae3f-4641-b6e3-7a2429781f33",
            "imageUrl": "https://placehold.co/640x960?text=JKT48+EVENT",
            "title": "THE BATTLE: DANCING QUEENS",
            "description": 'THE BATTLE: DANCING QUEEN akan menghadirkan para member JKT48 dengan skill dance terbaik! Dalam acara ini, mereka akan saling berhadapan dalam sebuah battle untuk menunjukkan siapa yang pantas menyandang gelar "Dancing Queen". Tak hanya itu, mereka juga akan menghadapi tantangan untuk menguji kreativitas, kecepatan, dan kekompakan. Siapakah member yang akan membuktikan diri sebagai dancer terbaik?',
            "type": "event",
            "active": False,
        },
        {
            "setlistId": "85d1807a-6143-4306-be45-3798d7cc321b",
            "imageUrl": "https://placehold.co/640x960?text=JKT48+EVENT",
            "title": "CATUR ASTA",
            "description": 'Menampilkan sisi lain dari kehidupan sekelompok manusia yang bekerja dalam sebuah kantor "Ahensi Kreatif" di salah satu kota besar di Indonesia. Seringkali kita dihadapkan pada berbagai pilihan yang menyulitkan dalam dinamika pekerjaan. Bahkan beberapa dari kalian mungkin akan memilih takut "deadline" daripada takut hantu. Dikemas dalam dialog yang "satire"- siap menampar para budak korporat (baca; kita) yang berada dalam frekuensi yang sama. Pepatah mengatakan "Rejeki sudah ada Signature", namun apakah benar demikian? Simak kisahnya yang diracik semanis teh es buatan Marlina Sihantam Meja! Kind reminder: Sampai bertemu di First Alignment, undangan sudah kami kirimkan Cc email masing-masing!',
            "type": "event",
            "active": False,
        },
        {
            "setlistId": "81d1463b-99ef-4704-82f8-bd1705b8644d",
            "imageUrl": "https://placehold.co/640x960?text=JKT48+EVENT",
            "title": "FAMILY48",
            "description": "Family48 is back! Dalam acara ini, kita akan bersama-sama menyaksikan member menebak jawaban terbanyak dari setiap pertanyaan yang telah melalui sebuah survei khusus. Kecepatan berpikir dan kreativitas tentu menjadi modal yang sangat penting untuk menemukan setiap jawaban. Saksikan keseruannya, hanya di JKT48 Theater!",
            "type": "event",
            "active": False,
        },
        {
            "setlistId": "4aedcfc1-9753-4c50-a619-68fa6c2564f1",
            "imageUrl": "https://placehold.co/640x960?text=JKT48+EVENT",
            "title": "QUIT GAME",
            "description": "QUIT GAME adalah sebuah acara spesial Ramadan yang mengusung tema game show. Di acara ini, para member akan dihadapkan pada berbagai tantangan permainan yang tidak hanya menguji kreativitas, tetapi juga mengasah kerja sama tim dan fokus. Setiap tantangan dirancang untuk mengetes seberapa solid dan kompak para member dalam menghadapi rintangan yang diberikan. Apakah mereka bisa melewati setiap tantangan dengan sukses? Atau justru akan menyerah di tengah jalan?",
            "type": "event",
            "active": False,
        },
        {
            "setlistId": "51183b54-b1c9-4c24-b3a7-6ecd16b626bc",
            "imageUrl": "https://placehold.co/640x960?text=JKT48+EVENT",
            "title": "SELEKSI PMDK",
            "description": 'Panggilan untuk setiap member berprestasi di JKT48 untuk mengikuti Seleksi Penelusuran Minat dan Kemampuan 2025. Seleksi ini juga berlaku bagi kalian yang memiliki nilai rapor di atas rata-rata, untuk ikut menyaksikan bagaimana member JKT48 adu kecerdasan untuk mendapatkan predikat "Einstein di Masa Depan".',
            "type": "event",
            "active": False,
        },
    ]
